### ISSUE TITLE
logging protocol error during in error context/cleanup

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1013]
When quitting artiq_ctlmgr with ctrl-c, there is some race condition in the logging protocol. It might be because the writer doesn't exist yet as it was unable to connect.

```
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/selector_events.py", line 481, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 1066, 0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/rj/src/artiq/artiq/tools.py", line 207, in stop
    await asyncio.wait_for(self.task, None)
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/tasks.py", line 387, in wait_for
    return (yield from fut)
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/futures.py", line 383, in __iter__
    return self.result()  # May raise too.
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/home/rj/src/conda/envs/py35/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/rj/src/artiq/artiq/protocols/logging.py", line 185, in _do
    writer.close()
UnboundLocalError: local variable 'writer' referenced before assignment
```

**Comment by jordens** [comment]
Thanks!
