### ISSUE TITLE
browser/h5py: can't open files when dragged from FilesDock into ExperimentDock

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1014]
Could be the leading `/`, Windows filename/qt/h5py incompatibility.

```
artiq.browser.experiments:Could not retrieve expid from HDF5 file
Traceback (most recent call last):
  File "C:\Users\huntem01\AppData\Local\conda\conda\envs\artiq-4-1\lib\site-packages\artiq\browser\experiments.py", line 296, in load_hdf5_task
    with h5py.File(filename, "r") as f:
  File "C:\Users\huntem01\AppData\Local\conda\conda\envs\artiq-4-1\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\huntem01\AppData\Local\conda\conda\envs\artiq-4-1\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/C:/Users/huntem01/src/opticlock/results/2018-05-24/17/000000398-Lineshape.h5', errno = 22, error message = 'Invalid argument', flags = 0, o_flags = 0)
```

**Comment by sbourdeauducq** [comment]
Can you clarify what you mean by "explorer" and "experiment"?
