### ISSUE TITLE
Sayma SAWG setting frequency1 causes lock-up 

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1067]
```
[     0.003882s]  INFO(runtime): software version 4.0.dev+1133.g0b086225
[     0.010234s]  INFO(runtime): gateware version 4.0.dev+1133.g0b086225
```

If only setting frequency0 the following can be run many times in succession using artiq_run. 

If frequency1.set is uncommented the liklihood of the core device locking up on the first call of artiq_run is 5/6. In the 1/6 case the core device locked up after calling artiq_run a second time. So this looks reproducible on my end. 

```
from artiq.experiment import *

class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_sma_out")
        self.sawgs = [self.get_device("sawg"+str(i)) for i in range(8)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)
        freq0 = 210*MHz
        amp1 = 0.5
        for sawg in self.sawgs:
            sawg.reset()
            delay(500*us)
            sawg.frequency0.set(freq0)
            sawg.amplitude1.set(amp1)
            #sawg.frequency1.set(30*MHz)
```

**Comment by jbqubit** [comment]
There's nothing printed on the UART. Setting frequency2 also seems to trigger same behavior. 

```
$ artiq_run repository/sines.py
Traceback (most recent call last):
  File "/home/britton/miniconda3/envs/artiq-dev/bin/artiq_run", line 11, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_run')()
  File "/home/britton/artiq-dev/artiq/artiq/frontend/artiq_run.py", line 219, in main
    return run(with_file=True)
  File "/home/britton/artiq-dev/artiq/artiq/frontend/artiq_run.py", line 205, in run
    raise exn
  File "/home/britton/artiq-dev/artiq/artiq/frontend/artiq_run.py", line 198, in run
    exp_inst.run()
  File "/home/britton/artiq-dev/artiq/artiq/language/core.py", line 53, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/core.py", line 126, in run
    self.comm.check_system_info()
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/comm_kernel.py", line 214, in check_system_info
    self._write_empty(Request.SystemInfo)
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/comm_kernel.py", line 179, in _write_empty
    self._write_header(ty)
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/comm_kernel.py", line 171, in _write_header
    self.open()
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/comm_kernel.py", line 84, in open
    self.socket = initialize_connection(self.host, self.port, **kwargs)
  File "/home/britton/artiq-dev/artiq/artiq/coredevice/comm.py", line 27, in initialize_connection
    sock = socket.create_connection((host, port), 5.0)
  File "/home/britton/miniconda3/envs/artiq-dev/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/home/britton/miniconda3/envs/artiq-dev/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Comment by sbourdeauducq** [comment]
Can you try by using the startup kernel? Likely there is intermittent memory/gateware corruption (did you rework the HMC7043 reset?) and running the whole TCP/IP stack is more likely to crash than running simpler code. Also disconnect Ethernet during the test so that the CPU doesn't have to process network broadcasts.

**Comment by sbourdeauducq** [comment]
It could be that it's longer kernels loaded through Ethernet that cause crashes, not frequency1 itself.

**Comment by jbqubit** [comment]
- 4.0.dev+1133.g0b086225
- Sayma_AMC s/n -6 (the one I've been using for two weeks now) 
   - memtests and locks fail in fewer than 1/55 previous boots
   - Ethernet works fine on this board interactively when just working with frequency 0
- HMC7043 reset pullup applied 
- running as startup kernel 

```
from artiq.experiment import *

class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        # self.setattr_device("ttl_sma_out")
        self.sawgs = [self.get_device("sawg"+str(i)) for i in range(8)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)
        for sawg in self.sawgs:
            sawg.reset()
            delay(500*us)
            sawg.amplitude1.set(100*MHz)
            sawg.frequency1.set(100*MHz)
```

```
|  \/  (_) ___|  ___  / ___|
| |\/| | \___ \ / _ \| |    
| |  | | |___) | (_) | |___ 
|_|  |_|_|____/ \___/ \____|

MiSoC Bootloader
Copyright (c) 2017-2018 M-Labs Limited

Bootloader CRC passed
Gateware ident 4.0.dev+1133.g0b086225
Initializing SDRAM...
DQS initial delay: 101 taps
Write leveling scan:
Module 3:
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111011001000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 2:
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001001111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111100011000000000000000000000000000000000000000000000000000000000000000000
Module 1:
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 0:
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
DQS initial delay: 101 taps
Write leveling: 92 102 123 118 done
Read leveling scan:
Module 3:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110011111000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 2:
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000001111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 1:
00000000000000000000000000000000000000000000000000000000000000000011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101001110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Module 0:
00000000000000000000000000000000000000000000000000000000111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111110111100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
Read leveling: 182+-77 173+-85 152+-78 139+-83 done
SDRAM initialized
Memory test passed

Booting from flash...
Starting firmware.
[     0.000007s]  INFO(runtime): ARTIQ runtime starting...
[     0.003882s]  INFO(runtime): software version 4.0.dev+1133.g0b086225
[     0.010232s]  INFO(runtime): gateware version 4.0.dev+1133.g0b086225
[     0.016612s]  INFO(runtime): log level set to INFO by default
[     0.022317s]  INFO(runtime): UART log level set to INFO by default
[     0.028456s]  INFO(board_artiq::serwb): waiting for AMC/RTM serwb bridge to be ready...
[     0.063183s]  INFO(board_artiq::serwb): done.
[     0.066214s]  INFO(board_artiq::serwb): RTM to AMC Link test
[     1.548257s]  INFO(board_artiq::serwb): 0 errors
[     1.551559s]  INFO(board_artiq::serwb): AMC to RTM Link test
[     3.033608s]  INFO(board_artiq::serwb): 0 errors
[     3.036906s]  INFO(board_artiq::serwb): Wishbone test...
[     4.968964s]  INFO(board_artiq::serwb): 0 errors
[     4.972269s]  INFO(board_artiq::serwb): AMC serwb settings:
[     4.977818s]  INFO(board_artiq::serwb):   bitslip: 31
[     4.982854s]  INFO(board_artiq::serwb):   ready: 1
[     4.987630s]  INFO(board_artiq::serwb):   error: 0
[     4.992405s]  INFO(board_artiq::serwb): RTM serwb settings:
[     4.997971s]  INFO(board_artiq::serwb):   bitslip: 14
[     5.003007s]  INFO(board_artiq::serwb):   ready: 1
[     5.007783s]  INFO(board_artiq::serwb):   error: 0
[     5.012793s]  INFO(board_artiq::serwb): RTM gateware version 4.0.dev+1133.g0b086225
[     5.020197s]  INFO(runtime): press 'e' to erase startup and idle kernels...
[     6.020007s]  INFO(runtime): continuing boot
[     6.023066s]  INFO(board_artiq::hmc830_7043::hmc830): HMC830 found
[     6.029134s]  INFO(board_artiq::hmc830_7043::hmc830): loading configuration...
[     6.036642s]  INFO(board_artiq::hmc830_7043::hmc830):   ...done
[     6.042230s]  INFO(board_artiq::hmc830_7043::hmc830): waiting for lock...
[     6.049036s]  INFO(board_artiq::hmc830_7043::hmc830):   ...locked
[     6.055081s]  INFO(board_artiq::hmc830_7043::hmc7043): enabling hmc7043
[     6.061956s]  INFO(board_artiq::hmc830_7043::hmc7043): HMC7043 found
[     6.068035s]  INFO(board_artiq::hmc830_7043::hmc7043): loading configuration...
[     6.077315s]  INFO(board_artiq::hmc830_7043::hmc7043):   ...done
[     6.082369s]  INFO(board_artiq::ad9154): AD9154-0 found
[     6.097507s]  INFO(board_artiq::ad9154): AD9154-0 initializing...
[     6.110435s]  INFO(board_artiq::ad9154):   ...done
[     6.184322s]  INFO(board_artiq::ad9154): AD9154-0 running PRBS test...
[     7.190698s]  INFO(board_artiq::ad9154):   ...passed
[     7.194357s]  INFO(board_artiq::ad9154): AD9154-0 running STPL test...
[     7.201146s]  INFO(board_artiq::ad9154):   c0 errors: 0
[     7.206350s]  INFO(board_artiq::ad9154):   c1 errors: 0
[     7.211560s]  INFO(board_artiq::ad9154):   c2 errors: 0
[     7.216770s]  INFO(board_artiq::ad9154):   c3 errors: 0
[     7.221694s]  INFO(board_artiq::ad9154):   ...passed
[     7.226643s]  INFO(board_artiq::ad9154): AD9154-0 SYSREF scan:
[     7.496572s]  INFO(board_artiq::ad9154):   phase: 25, sync error: 449
[     7.826769s]  INFO(board_artiq::ad9154):   phase: 57, sync error: 450
[     7.831908s]  INFO(board_artiq::ad9154):   phase min: Some(25), phase max: Some(56)
[     7.839549s]  INFO(board_artiq::ad9154): AD9154-0 setting SYSREF phase to 88
[     7.856934s]  INFO(board_artiq::ad9154): AD9154-0 initializing...
[     7.869826s]  INFO(board_artiq::ad9154):   ...done
[     7.944034s]  INFO(board_artiq::ad9154): AD9154-1 found
[     7.958233s]  INFO(board_artiq::ad9154): AD9154-1 initializing...
[     7.971121s]  INFO(board_artiq::ad9154):   ...done
[     8.044996s]  INFO(board_artiq::ad9154): AD9154-1 running PRBS test...
[     9.051366s]  INFO(board_artiq::ad9154):   ...passed
[     9.055025s]  INFO(board_artiq::ad9154): AD9154-1 running STPL test...
[     9.061810s]  INFO(board_artiq::ad9154):   c0 errors: 0
[     9.067019s]  INFO(board_artiq::ad9154):   c1 errors: 0
[     9.072229s]  INFO(board_artiq::ad9154):   c2 errors: 0
[     9.077439s]  INFO(board_artiq::ad9154):   c3 errors: 0
[     9.082361s]  INFO(board_artiq::ad9154):   ...passed
[     9.087310s]  INFO(board_artiq::ad9154): AD9154-1 SYSREF scan:
[     9.347078s]  INFO(board_artiq::ad9154):   phase: 24, sync error: 449
[     9.677270s]  INFO(board_artiq::ad9154):   phase: 56, sync error: 450
[     9.682406s]  INFO(board_artiq::ad9154):   phase min: Some(24), phase max: Some(55)
[     9.690047s]  INFO(board_artiq::ad9154): AD9154-1 setting SYSREF phase to 88
[     9.707434s]  INFO(board_artiq::ad9154): AD9154-1 initializing...
[     9.720326s]  INFO(board_artiq::ad9154):   ...done
[     9.794192s]  INFO(board_artiq::hmc542): card 0 channel 0 set to 4 dB
[     9.801438s]  INFO(board_artiq::hmc542): card 0 channel 1 set to 4 dB
[     9.808675s]  INFO(board_artiq::hmc542): card 1 channel 0 set to 4 dB
[     9.815912s]  INFO(board_artiq::hmc542): card 1 channel 1 set to 4 dB
[     9.823150s]  INFO(board_artiq::hmc542): card 2 channel 0 set to 4 dB
[     9.830386s]  INFO(board_artiq::hmc542): card 2 channel 1 set to 4 dB
[     9.837624s]  INFO(board_artiq::hmc542): card 3 channel 0 set to 4 dB
[     9.844861s]  INFO(board_artiq::hmc542): card 3 channel 1 set to 4 dB
[     9.852160s]  INFO(runtime): using MAC address 00-0a-35-03-1e-75
[     9.856956s]  INFO(runtime): using IP address 192.168.1.75
[     9.864001s]  INFO(runtime::mgmt): management interface active
[     9.877306s]  INFO(runtime::session): accepting network sessions
[     9.891505s]  INFO(runtime::session): running startup kernel
[     9.922865s]  INFO(runtime::kern_hwreq): resetting RTIO
[     9.929121s]  INFO(runtime::session): startup kernel finished
@ 0x4001dd1c
```

Ran this same experiment several more times.  
- no output on UART, no RF output, no response to ping
- no output on UART, amplitude modulation 100 MHz tone, no response to ping
- no output on UART, amplitude modulation 100 MHz tone, no response to ping
- UART outputs five lines filled with ```@ ```, amplitude modulation 100 MHz tone, no response to ping

Now disconnect SATA0 (Ethernet cable). 
- no output on UART, amplitude modulation 100 MHz tone
- no output on UART, amplitude modulation 100 MHz tone
- no output on UART, amplitude modulation 100 MHz tone

Reconnect SATA0 (Ethernet cable). Change frequency1 to frequency0 in above experiment. 
- no output on UART, amplitude modulation 100 MHz tone, no response to ping
- no output on UART, amplitude modulation 100 MHz tone, no response to ping
- no output on UART, amplitude modulation 100 MHz tone, no response to ping

Reduce @kernel in startup kernel to nothing but ```self.core.reset()```.
- can pin board
- can pin board
- can pin board

**Comment by jbqubit** [comment]
Edited previous post to strike ~~Ethernet works fine on this board interactively when just working with frequency 0~~

**Comment by jbqubit** [comment]
On this same board I can repeatedly run experiments that don't involve SAWG interactively over Ethernet. 

```
from artiq.experiment import *


class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_sma_out")
        self.t_list = self.linspace(1*us, 133*us, 100)

    def linspace(self, start, stop, num):
        dx = (stop-start)/(num-1) 
        return [start+n*dx for n in range(num)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)
        self.ttl_sma_out.output()

        while True:
            self.k3()            

    @kernel
    def k3(self):
        for t in self.t_list:
            delay(20*us)
            self.ttl_sma_out.pulse(t)
```

**Comment by sbourdeauducq** [comment]
#1065
