### ISSUE TITLE
Cannot construct bytes object in kernel

### ISSUE THREAD

**Issue by jonaskeller** [m-labs/artiq#1077]
Using `3.6py_40+gite8092f6f` on Windows 7 64bit with a KC705, `nist_qc2` gateware.

Not sure if this is meant to work, but calling, e.g.

	var = bytes([0xff])

(the value of the literal / number of list items doesn't matter) in a kernel results in

	ERROR:worker(16391,bytes_error_test.py):root:Terminating with exception (IndexError: list index out of range)
	Traceback (most recent call last):
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\master\worker_impl.py", line 279, in main
		exp_inst.run()
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\language\core.py", line 53, in run_on_core
		return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\coredevice\core.py", line 124, in run
		self.compile(function, args, kwargs, set_result)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\coredevice\core.py", line 107, in compile
		library = target.compile_and_link([module])
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\targets.py", line 184, in compile_and_link
		return self.link([self.assemble(self.compile(module)) for module in modules])
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\targets.py", line 184, in <listcomp>
		return self.link([self.assemble(self.compile(module)) for module in modules])
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\targets.py", line 138, in compile
		llmod = module.build_llvm_ir(self)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\module.py", line 89, in build_llvm_ir
		attribute_writeback=self.attribute_writeback)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\transforms\llvm_ir_generator.py", line 492, in process

		self.process_function(func)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\transforms\llvm_ir_generator.py", line 654, in process_function
		llinsn = getattr(self, "process_" + type(insn).__name__)(insn)
	  File "C:\Anaconda3\envs\artiq3.6\lib\site-packages\artiq\compiler\transforms\llvm_ir_generator.py", line 700, in process_Alloc
		llsize = self.map(insn.operands[0])
	IndexError: list index out of range
	ERROR:master:artiq.master.scheduler:got worker exception in run stage, deleting RID 16391

**Comment by jonaskeller** [comment]
Great, thanks for fixing this and 1076 so quickly! I'll test both once there is a build.
