### ISSUE TITLE
Gateware build error when instantiating multiple SUServo

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#1201]
# Bug Report
## One-Line Summary
Instantiating multiple SUServo in a gateware target causes a Migen error.

### Steps to Reproduce
Instantiate 2 SUServos in a gateware target:
```python
eem.SUServo.add_std(
    self, eems_sampler=(9,8),
    eems_urukul0=(1, 0), eems_urukul1=(3, 2))

eem.SUServo.add_std(
    self, eems_sampler=(11, 10),
    eems_urukul0=(5, 4), eems_urukul1=(7, 6))
```

Gives the error:
```
$ python -m artiq.gateware.targets.kasli_hoa2 -V satellite
SUServo (EEM9) starting at RTIO channel 0
SUServo (EEM11) starting at RTIO channel 12
Traceback (most recent call last):
  File "C:\Users\Chris\Miniconda3\envs\artiq-test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Chris\Miniconda3\envs\artiq-test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\scratch\artiq\artiq\gateware\targets\kasli_hoa2.py", line 107, in <module>
    main()
  File "C:\scratch\artiq\artiq\gateware\targets\kasli_hoa2.py", line 103, in main
    build_artiq_soc(soc, builder_argdict(args))
  File "C:\scratch\artiq\artiq\build_soc.py", line 49, in build_artiq_soc
    builder.build()
  File "C:\Users\Chris\Miniconda3\envs\artiq-test\lib\site-packages\misoc\integration\builder.py", line 178, in build
    self.soc.finalize()
  File "c:\scratch\migen\migen\fhdl\module.py", line 171, in finalize
    raise ValueError("Multiple submodules with local clock domains cannot have the same name")
ValueError: Multiple submodules with local clock domains cannot have the same name
```

### Your System
Using Artiq commit e3cfbfed

**Comment by sbourdeauducq** [comment]
I suppose this is because of the ``ret`` clock domain in ``adc_ser.py``; since all the modules in the hierarchy are anonymous or named the same, migen does not know how to rename them when there are multiple ones.
