### ISSUE TITLE
Kernel executions occasionally hangs

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#1263]
# Bug Report

## One-Line Summary

Kernel executions occasionally (once every hour or so) hangs. The core device remains responsive, the problematic experiment can be killed, and the core device returns to normal operation without restarting.

## Issue Details

When this issue occurs experiments seem stuck in an infinite loop - no visible output events are generated. The core device is still pingable, and still successfully force-terminates the experiment. When this problem has occurred the core analyser cannot retrieve the RTIO trace, and gives an error:
```
$ artiq_coreanalyzer -d dump.raw
Traceback (most recent call last):
  File "/home/ion/miniconda3/envs/artiq/bin/artiq_coreanalyzer", line 11, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_coreanalyzer')()
  File "/home/ion/scratch/artiq/artiq/frontend/artiq_coreanalyzer.py", line 54, in main
    decoded_dump = decode_dump(dump)
  File "/home/ion/scratch/artiq/artiq/coredevice/comm_analyzer.py", line 112, in decode_dump
    messages.append(decode_message(data[position:position+32]))
  File "/home/ion/scratch/artiq/artiq/coredevice/comm_analyzer.py", line 80, in decode_message
    ExceptionType(exception_type))
  File "/home/ion/miniconda3/envs/artiq/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/home/ion/miniconda3/envs/artiq/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 252 is not a valid ExceptionType
```

After a dead experiment has been force quit, subsequent experiments sometimes have the same problem. I don't have enough evidence to be certain, but it seems like the core device only behaves normally after core.reset() has been called.

I have seen this issue with different experiments of varying complexity. The simplest is an experiment that only calls break_realtime() followed by a Zotino init().

### Your System

* ARTIQ version: ea431b6982d67e29778ef5ca1ca82d9ef8096385
* Hardware involved: Kasli

**Comment by cjbe** [comment]
This and #1264 seem to be due to bad gateware.

These problems started after adding a Grabber EEM interface to my gateware. Removing the Grabber interface from the gateware (and not changing anything else) seems to have stopped this problem occurring. 

I guess the problem is due to a bad false path constraint on the Grabber - I am using the Grabber on a DRTIO master and used the constraint:
```python
self.platform.add_false_path_constraints(self.drtio_transceiver.gtp0.txoutclk, self.grabber0.deserializer.cd_cl.clk)
```
