### ISSUE TITLE
conda install artiq fails due to malformed version string '0.9.10~a6d5e28'

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#132]
```bash
rabi@68810artiq1:~$ conda install artiq
Fetching package metadata: ......
Solving package specifications: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 140, in __call__
    res = cache[key]
KeyError: (<function Resolve.get_pkgs at 0x7f32244b5840>, (MatchSpec('pyqtgraph'),), frozenset({('max_only', False)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 337, in install
    update_deps=args.update_deps)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 412, in install_actions
    update_deps=update_deps):
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 955, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 709, in solve2
    dists = self.get_dists(specs)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 623, in get_dists
    dists.update(self.all_deps(pkg.fn, max_only=max_only))
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 503, in all_deps
    add_dependents(root_fn, max_only=max_only)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 482, in add_dependents
    for pkg2 in self.get_pkgs(ms, max_only=max_only):
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 142, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 450, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 450, in <listcomp>
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 151, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '0.9.10~a6d5e28': invalid character(s).
rabi@68810artiq1:~$ conda install pyqtgraph
Fetching package metadata: ......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 140, in __call__
    res = cache[key]
KeyError: (<function Resolve.get_pkgs at 0x7fcf42a8b840>, (MatchSpec('pyqtgraph'),), frozenset({('max_only', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabi/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 337, in install
    update_deps=args.update_deps)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 407, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 351, in add_defaults_to_specs
    for spec in specs
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 352, in <genexpr>
    for fn in r.get_max_dists(MatchSpec(spec))
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 469, in get_max_dists
    pkgs = self.get_pkgs(ms, max_only=True)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 142, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 450, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 450, in <listcomp>
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 151, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '0.9.10~a6d5e28': invalid character(s).
rabi@68810artiq1:~$ 
rabi@68810artiq1:~$ 
rabi@68810artiq1:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.1
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.8.0
     root environment : /home/rabi/anaconda3  (writable)
  default environment : /home/rabi/anaconda3
     envs directories : /home/rabi/anaconda3/envs
        package cache : /home/rabi/anaconda3/pkgs
         channel URLs : http://conda.anaconda.org/m-labs/channel/dev/linux-64/
                        http://conda.anaconda.org/m-labs/channel/dev/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/rabi/.condarc
    is foreign system : False

rabi@68810artiq1:~$ conda list
# packages in environment at /home/rabi/anaconda3:
#
_license                  1.1                      py34_0  
abstract-rendering        0.5.1                np19py34_0  
alabaster                 0.7.3                    py34_0  
anaconda                  2.3.0                np19py34_0  
argcomplete               0.8.9                    py34_0  
astropy                   1.0.3                np19py34_0  
babel                     1.3                      py34_0  
bcolz                     0.9.0                np19py34_0  
beautiful-soup            4.3.2                    py34_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py34_0  
bitarray                  0.8.1                    py34_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py34_0  
blz                       0.6.2                np19py34_1  
bokeh                     0.9.0                np19py34_0  
boto                      2.38.0                   py34_0  
bottleneck                1.0.0                np19py34_0  
certifi                   14.05.14                 py34_0  
cffi                      1.1.0                    py34_0  
clyent                    0.3.4                    py34_0  
colorama                  0.3.3                    py34_0  
conda                     3.18.1                   py34_0  
conda-build               1.14.1                   py34_0  
conda-env                 2.4.2                    py34_0  
configobj                 5.0.6                    py34_0  
cryptography              0.9.1                    py34_0  
curl                      7.43.0                        0  
cython                    0.22.1                   py34_0  
cytoolz                   0.7.3                    py34_0  
datashape                 0.4.5                np19py34_0  
decorator                 3.4.2                    py34_0  
docutils                  0.12                     py34_0  
dynd-python               0.6.5                np19py34_0  
fastcache                 1.0.2                    py34_0  
flask                     0.10.1                   py34_1  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
greenlet                  0.4.7                    py34_0  
h5py                      2.5.0                np19py34_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py34_0  
ipython                   3.2.0                    py34_0  
ipython-notebook          3.2.0                    py34_0  
ipython-qtconsole         3.2.0                    py34_0  
itsdangerous              0.24                     py34_0  
jdcal                     1.0                      py34_0  
jedi                      0.8.1                    py34_0  
jinja2                    2.7.3                    py34_1  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
libdynd                   0.6.5                         0  
libffi                    3.0.13                        0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.5.0                    py34_0  
lxml                      3.4.4                    py34_0  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_2  
mistune                   0.5.1                    py34_1  
mock                      1.0.1                    py34_0  
multipledispatch          0.4.7                    py34_0  
networkx                  1.9.1                    py34_0  
nltk                      3.0.3                np19py34_0  
nose                      1.3.7                    py34_0  
numba                     0.19.1               np19py34_0  
numexpr                   2.4.3                np19py34_0  
numpy                     1.9.2                    py34_0  
odo                       0.3.2                np19py34_0  
openpyxl                  1.8.5                    py34_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py34_0  
patsy                     0.3.0                np19py34_0  
pep8                      1.6.2                    py34_0  
pillow                    2.8.2                    py34_0  
pip                       7.1.2                    py34_0  
ply                       3.6                      py34_0  
psutil                    2.2.1                    py34_0  
ptyprocess                0.4                      py34_0  
py                        1.4.27                   py34_0  
pyasn1                    0.1.7                    py34_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.14                     py34_0  
pycrypto                  2.6.1                    py34_0  
pycurl                    7.19.5.1                 py34_2  
pyflakes                  0.9.2                    py34_0  
pygments                  2.0.2                    py34_0  
pyopenssl                 0.15.1                   py34_1  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.3                   py34_1  
pytables                  3.2.0                np19py34_0  
pytest                    2.7.1                    py34_0  
python                    3.4.3                         1  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.4                   py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_0  
qt                        4.8.6                         3  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py34_0  
requests                  2.8.0                    py34_0  
rope                      0.9.4                    py34_1  
rope-py3k-0.9.4           1                         <pip>
runipy                    0.1.3                    py34_0  
scikit-image              0.11.3               np19py34_0  
scikit-learn              0.16.1               np19py34_0  
scipy                     0.15.1               np19py34_0  
setuptools                18.3.2                   py34_0  
sip                       4.16.5                   py34_0  
six                       1.9.0                    py34_0  
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.5.2                  py34_0  
spyder-app                2.3.5.2                  py34_0  
sqlalchemy                1.0.5                    py34_0  
sqlite                    3.8.4.1                       1  
statsmodels               0.6.1                np19py34_0  
sympy                     0.7.6                    py34_0  
system                    5.8                           2  
tables                    3.2.0                     <pip>
terminado                 0.5                      py34_0  
theano                    0.7.0                np19py34_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py34_0  
tornado                   4.2                      py34_0  
ujson                     1.33                     py34_0  
util-linux                2.21                          0  
werkzeug                  0.10.4                   py34_0  
wheel                     0.26.0                   py34_1  
xlrd                      0.9.3                    py34_0  
xlsxwriter                0.7.3                    py34_0  
xlwt                      1.0.0                    py34_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
rabi@68810artiq1:~$ 
```

**Comment by sbourdeauducq** [comment]
Daniel is probably using Yann's outdated repository.
