### ISSUE TITLE
Coreanalyzer can't handle RTIO underflow exceptions raised by spi2 devices

### ISSUE THREAD

**Issue by jonaskeller** [m-labs/artiq#1377]
# Bug Report

## One-Line Summary

The `coreanalyzer` tool exits with an error when run after an RTIO underflow was caused by an `SPIMaster` device (module `artiq.coredevice.spi2`).

### Steps to Reproduce

1.  Run this experiment:

```
from artiq.experiment import *

class cause_underflow(EnvExperiment):
    '''cause an RTIO underflow'''
    def build(self):
        self.setattr_device("core")    
        self.setattr_device("spi0")

    @kernel
    def run(self):
        self.core.reset()
        at_mu(self.core.get_rtio_counter_mu())
        self.spi0.set_config_mu(0, 32, 24, 1)

```

Relevant `device_db.py` entry:
```
    "spi0": {
        "type": "local",
        "module": "artiq.coredevice.spi2",
        "class": "SPIMaster",
       "arguments": {"channel": 46}    
    }
```

2. Run `artiq_coreanalyzer -w output.vcd`

### Actual (undesired) Behavior
```

Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq4.0\Scripts\artiq_coreanalyzer-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Anaconda3\envs\artiq4.0\lib\site-packages\artiq\frontend\artiq_coreanalyzer.py", line 57, in main
    decoded_dump)
  File "C:\Anaconda3\envs\artiq4.0\lib\site-packages\artiq\coredevice\comm_analyzer.py", line 543, in decoded_dump_to_vcd
    channel_handlers[message.channel].process_message(message)
  File "C:\Anaconda3\envs\artiq4.0\lib\site-packages\artiq\coredevice\comm_analyzer.py", line 363, in process_message
    data = message.data
AttributeError: 'ExceptionMessage' object has no attribute 'data'
```

### Your System (omit irrelevant parts)

* Operating System: Windows 7 64bit
* ARTIQ version: 4.0 0+gitbf50dcf7

**Comment by sbourdeauducq** [comment]
Is that only spi2 devices, or all devices?

**Comment by jonaskeller** [comment]
If I cause the underflow using a `TTLOut` device, it doesn't occur.

**Comment by jordens** [comment]
Yes. Thanks for submitting and analyzing!
