### ISSUE TITLE
compiler: Internal error instead of diagnostic on type mismatch

### ISSUE THREAD

**Issue by dnadlinger** [m-labs/artiq#1397]
On latest master (86e1924493b6764944a363928e60fcaa2fa82fcf), this

```py
from artiq.experiment import *

class AnnotationMismatch(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def foo(self) -> TTuple([TInt32, TFloat]):
        return (0, 0)  # <- Note type mismatch in the second argument.

    @kernel
    def run(self):
        self.foo()
```

doesn't produce a diagnostic as expected, but rather fails with an internal compiler error:

```
Traceback (most recent call last):
  File "<artiq>/compiler/transforms/inferencer.py", line 28, in _unify
    typea.unify(typeb)
  File "<artiq>/compiler/types.py", line 89, in unify
    self.find().unify(other)
  File "<artiq>/compiler/types.py", line 134, in unify
    raise UnificationError(self, other)
artiq.compiler.types.UnificationError: (artiq.compiler.types.TInstance('artiq.compiler.builtins.TInt', OrderedDict([('__objectid__', artiq.compiler.types.TMono('int', OrderedDict([('width', artiq.compiler.types.TValue(32))])))])), artiq.compiler.types.TInstance('artiq.compiler.builtins.TFloat', OrderedDict([('__objectid__', artiq.compiler.types.TMono('int', OrderedDict([('width', artiq.compiler.types.TValue(32))])))])))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/artiq-dev/bin/artiq_run", line 11, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_run')()
  File "<artiq>/frontend/artiq_run.py", line 225, in main
    return run(with_file=True)
  File "<artiq>/frontend/artiq_run.py", line 211, in run
    raise exn
  File "<artiq>/frontend/artiq_run.py", line 204, in run
    exp_inst.run()
  File "<artiq>/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "<artiq>/coredevice/core.py", line 129, in run
    self.compile(function, args, kwargs, set_result)
  File "<artiq>/coredevice/core.py", line 105, in compile
    stitcher.finalize()
  File "<artiq>/compiler/embedding.py", line 709, in finalize
    inferencer.visit(self.typedtree)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 39, in visit
    return [self.visit(elt) for elt in obj]
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 39, in <listcomp>
    return [self.visit(elt) for elt in obj]
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "<artiq>/compiler/transforms/inferencer.py", line 1331, in visit_FunctionDefT
    self.generic_visit(node)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "<artiq>/compiler/transforms/inferencer.py", line 945, in visit_CallT
    self.generic_visit(node)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 39, in visit
    return [self.visit(elt) for elt in obj]
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 39, in <listcomp>
    return [self.visit(elt) for elt in obj]
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "<artiq>/compiler/transforms/inferencer.py", line 87, in visit_ListT
    self._makenotes_elts(node.elts, "a list element"))
  File "<artiq>/compiler/transforms/inferencer.py", line 55, in _unify
    loca, highlights, notes)
  File "/usr/local/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/diagnostic.py", line 53, in __init__
    raise ValueError("location and highlights must refer to the same source buffer")
ValueError: location and highlights must refer to the same source buffer
```

**Comment by sbourdeauducq** [comment]
Not a bug on NAC3
```python
from numpy import int32
from min_artiq import *

@nac3
class Demo:
    core: KernelInvariant[Core]

    def __init__(self):
        self.core = Core()

    @kernel
    def foo(self) -> tuple[int32, float]:
        return (0, 0)  # <- Note type mismatch in the second argument.

    @kernel
    def run(self):
        self.foo()


if __name__ == "__main__":
    Demo().run()
```

```
Cannot unify int32 with float at line 13 column 17
```
