### ISSUE TITLE
artiq_flash -H does not support PKCS#11 tokens

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1456]
```
Traceback (most recent call last):
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 479, in <module>
    main()
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 399, in main
    programmer = programmer_cls(client, preinit_script=args.preinit_command)
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 223, in __init__
    boardfile=self._transfer_script("board/{}.cfg".format(board)))
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 137, in _transfer_script
    return self._client.upload(script, rewriter)
  File "/home/sb/artiq/artiq/remoting.py", line 109, in upload
    rewritten = rewriter(local.read())
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 134, in rewriter
    return re.sub(rb"\[find (.+?)\]", repl, content, re.DOTALL)
  File "/nix/store/55b9ip7xkpimaccw9pa0vacy5q94f5xa-python3-3.7.6/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 133, in repl
    return self._transfer_script(match.group(1).decode()).encode()
  File "/home/sb/artiq/artiq/frontend/artiq_flash.py", line 137, in _transfer_script
    return self._client.upload(script, rewriter)
  File "/home/sb/artiq/artiq/remoting.py", line 113, in upload
    sftp = self.get_sftp()
  File "/home/sb/artiq/artiq/remoting.py", line 100, in get_sftp
    self.sftp = self.get_ssh().open_sftp()
  File "/home/sb/artiq/artiq/remoting.py", line 90, in get_ssh
    self.ssh.connect(self.host, username=self.username, sock=proxy)
  File "/nix/store/k706yd9r2z98j7k5g2w22bvazgpcv9jd-python3-3.7.6-env/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/nix/store/k706yd9r2z98j7k5g2w22bvazgpcv9jd-python3-3.7.6-env/lib/python3.7/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/nix/store/k706yd9r2z98j7k5g2w22bvazgpcv9jd-python3-3.7.6-env/lib/python3.7/site-packages/paramiko/client.py", line 740, in _auth
    self._transport.auth_publickey(username, key)
  File "/nix/store/k706yd9r2z98j7k5g2w22bvazgpcv9jd-python3-3.7.6-env/lib/python3.7/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/nix/store/k706yd9r2z98j7k5g2w22bvazgpcv9jd-python3-3.7.6-env/lib/python3.7/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Comment by sbourdeauducq** [comment]
Using ssh-agent (paramiko can connect to it) fixes the issue.
