### ISSUE TITLE
List/tuple/range variable declaration inside try/with statement causes compiler crash

### ISSUE THREAD

**Issue by lriesebos** [m-labs/artiq#1506]
# Bug Report

## One-Line Summary

When explicitly or implicitly declaring a list/tuple/range variable inside a try/with statement which initializes to the return value of a function, the compiler crashes with an internal type error related to the IR.

### Steps to Reproduce

See the following minimal examples. For the `try` statement I provided all three examples while I only provided one example for the `with` statement with the list. I assume the reader can imagine how the examples with the `with` statement and the range/tuple look like.

```python
from artiq.experiment import *


class TryVariableDeclarationListExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')
        self.data = [i for i in range(10)]

    @kernel
    def run(self):
        try:
            for _ in self.get_data():
                pass
        finally:
            pass

    @kernel
    def get_data(self) -> TList(TInt32):
        return self.data


class TryVariableDeclarationRangeExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')

    @kernel
    def run(self):
        try:
            for _ in self.get_data():
                pass
        finally:
            pass

    @kernel
    def get_data(self) -> TRange32:
        return range(10)


class TryVariableDeclarationTupleExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')
        self.a = 1
        self.b = 2

    @kernel
    def run(self):
        try:
            _, _ = self.get_tuple()
        finally:
            pass

    @kernel
    def get_tuple(self) -> TTuple([TInt32, TInt32]):
        return self.a, self.b


class MyContext:
    @kernel
    def __enter__(self):
        pass

    @kernel
    def __exit__(self, a, b, c):
        pass


class TryVariableDeclarationListContextExperiment(EnvExperiment):

    def build(self):
        self.setattr_device('core')
        self.data = [i for i in range(10)]
        self.context = MyContext()

    @kernel
    def run(self):
        with self.context:
            for _ in self.get_data():
                pass

    @kernel
    def get_data(self) -> TList(TInt32):
        return self.data

```

### Expected Behavior

All example experiments should compile without problems.

### Actual (undesired) Behavior

The errors for all experiments are practically the same. See the message below. The only difference are the actual types in the error. List: `{i32*, i32}* != i8*`, tuple: `{i32, i32}* != i8*`, and range: `{i32, i32, i32}* != i8*`.

```
ERROR:worker(48,try_variable_declaration.py):root:Terminating with exception (TypeError: Type of #1 arg mismatch: {i32*, i32}* != i8*)
Traceback (most recent call last):
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/master/worker_impl.py", line 290, in main
    exp_inst.run()
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/coredevice/core.py", line 129, in run
    self.compile(function, args, kwargs, set_result)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/coredevice/core.py", line 112, in compile
    library = target.compile_and_link([module])
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/targets.py", line 191, in compile_and_link
    return self.link([self.assemble(self.compile(module)) for module in modules])
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/targets.py", line 191, in <listcomp>
    return self.link([self.assemble(self.compile(module)) for module in modules])
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/targets.py", line 145, in compile
    llmod = module.build_llvm_ir(self)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/module.py", line 93, in build_llvm_ir
    attribute_writeback=self.attribute_writeback)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/transforms/llvm_ir_generator.py", line 519, in process
    self.process_function(func)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/transforms/llvm_ir_generator.py", line 680, in process_function
    llinsn = getattr(self, "process_" + type(insn).__name__)(insn)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/artiq/compiler/transforms/llvm_ir_generator.py", line 1496, in process_Invoke
    name=insn.name)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/llvmlite_artiq/ir/builder.py", line 814, in invoke
    cconv=cconv)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/llvmlite_artiq/ir/instructions.py", line 145, in __init__
    super(InvokeInstr, self).__init__(parent, func, args, name, cconv)
  File "/nix/store/bkxx7ynjqx1m51wdnqy0nbx97jb01g4j-python3-3.7.6-env/lib/python3.7/site-packages/llvmlite_artiq/ir/instructions.py", line 83, in __init__
    raise TypeError(msg)
TypeError: Type of #1 arg mismatch: {i32*, i32}* != i8*
```
### Workarounds

So far we found two workarounds for this bug, though we are not sure if these apply to all situations in which this bug can appear.
1. Declare the (implicit) variable before the `try`/`with` statement.
1. Put the body of the `try`/`with` statement in a separate function and call that function.

### Your System (omit irrelevant parts)

* Operating System: Ubuntu 18.04 and 20.04
* ARTIQ version: v5.7122.929b04da, installed through Nix
* Reproduced both for Kasli and KC705 target (to be expected for a compile error)

**Comment by dnadlinger** [comment]
Probably related to #1531.
