### ISSUE TITLE
plotting doesn't work for numpy arrays 

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#153]
```python
from artiq import *
import numpy as np
import time

class Scratch(EnvExperiment):
    """scratch exp"""

    def build(self):
        pass

    def run(self):
        while True:
            try:
                self.hist_nbins = 100
                self.hist_nmax = 200
                counts = []
                for i in range(10):
                    new_counts = np.random.poisson(100, size=10)
                    counts.append(new_counts)
                    hist, hist_bins = np.histogram(counts, self.hist_nbins,
                        range=(0, self.hist_nmax))

                    # set to numpy arrays
                    self.set_dataset("common_hist1_bins", hist_bins,
                                     broadcast=True, persist=True, save=False)
                    self.set_dataset("common_hist1_counts", hist, broadcast=True, persist=True, save=False)
                    time.sleep(0.1)

            except TerminationRequested:
                # record in Parameter DB the latest frequency which ought to be self.f
                self.set_artiq_datasets_if_changed()
                logging.info("Terminated gracefully")
```
Generates following error.
```bash
===== 2015.10.20 14:10:05 =====
Traceback (most recent call last):
  File "/home/jwbritto/anaconda3/envs/py35/lib/python3.5/site-packages/artiq/gui/displays.py", line 24, in on_accept
    create_cb(self.name.text(), self.get_input())
  File "/home/jwbritto/anaconda3/envs/py35/lib/python3.5/site-packages/artiq/gui/datasets.py", line 136, in create_display
    self.update_display_data(dsp)
  File "/home/jwbritto/anaconda3/envs/py35/lib/python3.5/site-packages/artiq/gui/datasets.py", line 104, in update_display_data
    for k in dsp.data_sources()})
  File "/home/jwbritto/anaconda3/envs/py35/lib/python3.5/site-packages/artiq/gui/displays.py", line 204, in update_data
    if y and len(x) == len(y) + 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by sbourdeauducq** [comment]
Note that you need to pause for the graceful termination to work.
