### ISSUE TITLE
Getting ValueError: DUC+oscillator phase/amplitude test failed during phaser.init()

### ISSUE THREAD

**Issue by sotirova** [m-labs/artiq#1532]
# Bug Report

## Summary

Trying to get a phaser baseband board to work for the first time
It has been flashed using a Vivado jtag as described in https://github.com/quartiq/phaser  
Currently getting ValueError: DUC+oscillator phase/amplitude test failed during phaser.init()

### Your System
* Misoc: a8a33f6
* Migen: c50ecde
* ARTIQ: eecd97c
* Hardware involved: phaser

### Error message

```
root:Terminating with exception (ValueError: DUC+oscillator phase/amplitude test failed)
Core Device Traceback (most recent call last):
  File "/home/ion/abaqus-master/repository/test_phaser.py", line 12, in __modinit__ (RA=+0x8c8)
    self.phaser0.init()
  File "<artiq>/coredevice/phaser.py", line -1, in ... artiq.coredevice.phaser.Phaser.init<artiq.coredevice.phaser.Phaser>(...) (RA=+0x2718)
    <unknown>
  File "<artiq>/coredevice/phaser.py", line 309, column 17, in ... artiq.coredevice.phaser.Phaser.init<artiq.coredevice.phaser.Phaser>(...)
    raise ValueError("DUC+oscillator phase/amplitude test failed")
    ^
ValueError(0): DUC+oscillator phase/amplitude test failed
Traceback (most recent call last):
  File "/home/ion/scratch/artiq/artiq/master/worker_impl.py", line 384, in main
    exp_inst.run()
  File "/home/ion/scratch/artiq/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/home/ion/scratch/artiq/artiq/coredevice/core.py", line 137, in run
    self.comm.serve(embedding_map, symbolizer, demangler)
  File "/home/ion/scratch/artiq/artiq/coredevice/comm_kernel.py", line 629, in serve
    self._serve_exception(embedding_map, symbolizer, demangler)
  File "/home/ion/scratch/artiq/artiq/coredevice/comm_kernel.py", line 621, in _serve_exception
    raise python_exn
ValueError: DUC+oscillator phase/amplitude test failed
```

**Comment by jordens** [comment]
This is https://github.com/quartiq/phaser/issues/5
Try `load.tcl`-ing the phaser bitstream again.
If that doesn't help please post on https://github.com/quartiq/phaser/issues/5
