### ISSUE TITLE
artiq.test.coredevice.test_embedding.ArrayQuotingTest fails on Zynq

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1539]
```
======================================================================
ERROR: test_quoting (artiq.test.coredevice.test_embedding.ArrayQuotingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/dqfdq864hrn1v8xs3glcrgd7zqcim70h-python3.8-artiq-6.7477.d672d2fc.beta/lib/python3.8/site-packages/artiq/test/coredevice/test_embedding.py", line 462, in test_quoting
    self.create(_ArrayQuoting).run()
  File "/nix/store/dqfdq864hrn1v8xs3glcrgd7zqcim70h-python3.8-artiq-6.7477.d672d2fc.beta/lib/python3.8/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/nix/store/dqfdq864hrn1v8xs3glcrgd7zqcim70h-python3.8-artiq-6.7477.d672d2fc.beta/lib/python3.8/site-packages/artiq/coredevice/core.py", line 135, in run
    self.comm.load(kernel_library)
  File "/nix/store/dqfdq864hrn1v8xs3glcrgd7zqcim70h-python3.8-artiq-6.7477.d672d2fc.beta/lib/python3.8/site-packages/artiq/coredevice/comm_kernel.py", line 363, in load
    raise LoadError(self._read_string())
artiq.coredevice.comm_kernel.LoadError: core1 failed to process data

----------------------------------------------------------------------
```

Device log:
```
[  3093.860055s] ERROR(runtime::kernel::core1): failed to load shared library: symbol lookup error: abort
```

**Comment by sbourdeauducq** [comment]
That's because this new test uses ``assert`` in the kernel, which the compiler implements with a detailed error logged and then a call to ``abort`` (see ``visit_Assert`` in ``artiq_ir_generator.py``). This is inconsistent with CPython behavior where a failed assert raises ``AssertionError``.

I'm not sure if this behavior is useful, maybe assert support should just be dropped from the compiler...

**Comment by dnadlinger** [comment]
Ack, looking into it.

**Comment by dnadlinger** [comment]
I've implemented asserts via `AssertionError`s, as I find them quite useful/natural to have. (Maybe my sense of style for Python is odd; who knows.) https://github.com/m-labs/artiq/pull/1541, still needs testing before merging.
