### ISSUE TITLE
Pythonparser is down on artiq 6.7582

### ISSUE THREAD

**Issue by KaifengC** [m-labs/artiq#1622]
# Bug Report

## One-Line Summary

Can not pass simple `hello test` in the recent artiq 6.7582

## Issue Details

I'm testing artiq 6.7582 with a simple `hello_test`：

```python
from artiq.experiment import *          


class Test(EnvExperiment):
    """Hello test
    """
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        print('hello')
```

I saw this error:

``` bash
(artiq) D:\artiq1>artiq_run hello_test.py
Traceback (most recent call last):
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\pythonparser\lexer.py", line 133, in __init__
    reserved = self._reserved[version]
KeyError: (3, 9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86183\anaconda3\envs\artiq\Scripts\artiq_run-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 225, in main
    return run(with_file=True)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 211, in run
    raise exn
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 204, in run
    exp_inst.run()
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\language\core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\core.py", line 129, in run
    self.compile(function, args, kwargs, set_result)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\core.py", line 104, in compile
    stitcher.stitch_call(function, args, kwargs, set_result)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\compiler\embedding.py", line 690, in stitch_call
    call_node = synthesizer.call(function, args, kwargs, callback)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\compiler\embedding.py", line 362, in call
    callee_node = self.quote(callee)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\compiler\embedding.py", line 256, in quote
    function_type = self.quote_function(value, self.expanded_from)
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\compiler\embedding.py", line 1089, in _quote_function
    self._quote_embedded_function(function,
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\artiq\compiler\embedding.py", line 905, in _quote_embedded_function
    lexer = source_lexer.Lexer(source_buffer, version=sys.version_info[0:2],
  File "C:\Users\86183\anaconda3\envs\artiq\lib\site-packages\pythonparser\lexer.py", line 135, in __init__
    raise NotImplementedError("pythonparser.lexer.Lexer cannot lex Python %s" %
NotImplementedError: pythonparser.lexer.Lexer cannot lex Python (3, 9)
```

The same code works perfectly on artiq 6.7522

The packages I have are: 

```bash
(artiq) D:\artiq1>conda list
# packages in environment at C:\Users\86183\anaconda3\envs\artiq:
#
# Name                    Version                   Build  Channel
artiq                     6.7582.c2248278               0    https://conda.m-labs.hk/artiq
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
binutils-or1k-linux       2.30                          0    https://conda.m-labs.hk/artiq
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
certifi                   2020.12.5        py39hcbf5309_1    conda-forge
cffi                      1.14.5           py39h0878f49_0    conda-forge
h5py                      3.1.0           nompi_py39hf27771d_100    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.0.1          default_h5c34c98_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libgit2                   1.1.0                h8648793_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
llvmlite-artiq            0+unknown                pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.20.1           py39h6635163_0    conda-forge
openssl                   1.1.1j               h8ffe710_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prettytable               2.0.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygit2                    1.5.0            py39hb82d6ee_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_7    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_7    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_7    conda-forge
pyqtchart                 5.12             py39h415ef7b_7    conda-forge
pyqtgraph                 0.11.1             pyhd3deb0d_0    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_7    conda-forge
pyreadline                2.1             py39hcbf5309_1003    conda-forge
python                    3.9.2           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-levenshtein        0.12.2           py39hb82d6ee_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pythonparser              1.3                           0    https://conda.m-labs.hk/artiq
qasync                    0.10.0                   pypi_0    pypi
qt                        5.12.9               h5909a2a_4    conda-forge
regex                     2020.11.13       py39hb82d6ee_1    conda-forge
scipy                     1.6.0            py39hc0c34ad_0    conda-forge
setuptools                49.6.0           py39hcbf5309_3    conda-forge
sipyco                    1.2                           0    https://conda.m-labs.hk/artiq
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
vc                        14.2                 hb210afc_3    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_3    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py39hcbf5309_1006    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
```

### Steps to Reproduce

1. install artiq 6.7582.
2. copy the `hello_test.py` and use `artiq_run hello_test.py`.

### Expected Behavior

Should get `hello` from the device.

Behavior

Get an error relatived to Pythonparser.

### Your System (omit irrelevant parts)

* Operating System: Win10
* ARTIQ version: artiq 6.7582
* Hardware involved: Sinara device

**Comment by sbourdeauducq** [comment]
Python 3.9 isn't supported. Please downgrade to 3.7.
(Normally the next conda channel update will cause automatic downgrade to 3.7, but generally conda needs a lot of manual intervention and workarounds.)
