### ISSUE TITLE
experiments intermittently get stuck in delete stage

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#167]
The scheduler's delete stage intermittently crashes due to a race condition with the subprocess. When this has happened, on master exit the following error trace is printed:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 330, in run_until_compl
ete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 301, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1162, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 432, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
ERROR:master:asyncio:Task exception was never retrieved
future: <Task finished coro=<Deleter._do() done, defined at /home/sb/NIST/artiq/
artiq/master/scheduler.py:380> exception=ProcessLookupError(3, 'No such process'
)>
Traceback (most recent call last):
  File "/home/sb/NIST/artiq/artiq/master/worker.py", line 93, in close
    await self._send(obj, cancellable=False)
  File "/home/sb/NIST/artiq/artiq/master/worker.py", line 126, in _send
    f.result()  # raise any exceptions
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/usr/lib/python3.5/asyncio/streams.py", line 304, in drain
    yield from self._protocol._drain_helper()
  File "/usr/lib/python3.5/asyncio/streams.py", line 194, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/home/sb/NIST/artiq/artiq/master/scheduler.py", line 383, in _do
    await self._delete(rid)
  File "/home/sb/NIST/artiq/artiq/master/scheduler.py", line 366, in _delete
    await pipeline.pool.delete(rid)
  File "/home/sb/NIST/artiq/artiq/master/scheduler.py", line 160, in delete
    await run.close()
  File "/home/sb/NIST/artiq/artiq/master/scheduler.py", line 102, in close
    await self.worker.close()
  File "/home/sb/NIST/artiq/artiq/master/worker.py", line 97, in close
    self.process.kill()
  File "/usr/lib/python3.5/asyncio/subprocess.py", line 125, in kill
    self._transport.kill()
  File "/usr/lib/python3.5/asyncio/base_subprocess.py", line 151, in kill
    self._proc.kill()
  File "/usr/lib/python3.5/subprocess.py", line 1769, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.5/subprocess.py", line 1759, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
ERROR:master:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<PrepareStage._do() running at /home/sb/NIST/artiq/artiq/master/scheduler.py:207> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:master:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<AnalyzeStage._do() running at /home/sb/NIST/artiq/artiq/master/scheduler.py:312> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:master:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<RunStage._do() running at /home/sb/NIST/artiq/artiq/master/scheduler.py:263> wait_for=<Future pending cb=[Task._wakeup()]>>``

**Comment by sbourdeauducq** [comment]
The problem comes from ``process.kill`` raising an exception if the process has already terminated. The exception can be safely ignored. The following program can demonstrate this:

```python
import asyncio


@asyncio.coroutine
def test():
    process = yield from asyncio.create_subprocess_exec("echo")
    yield from asyncio.sleep(1.0)
    # remove try/except to get the exception
    try:
        process.kill()
    except ProcessLookupError:
        pass
    yield from process.wait()


loop = asyncio.get_event_loop()
loop.run_until_complete(test())
loop.close()
```
