### ISSUE TITLE
Exception handling issues

### ISSUE THREAD

**Issue by pca006132** [m-labs/artiq#1815]
# Bug Report

## One-Line Summary

The current exception handling code may be sub-optimal.

## Issue Details

Related code:

https://github.com/m-labs/artiq/blob/bbac4770926048b3c0b434aede371a63d198ecd5/artiq/compiler/transforms/llvm_ir_generator.py#L1628

We currently emit `landingpad` as cleanups even if they may not be cleanup. We also did not specify the catch clauses. According to [LLVM exception handling docs](https://llvm.org/docs/ExceptionHandling.html#try-catch), a cleanup pad will always be entered and is usually being used to implement things like destructors. So if I understand it correctly, we will visit the catch block every time we return/raise an exception, regardless of the exception type, and perform a bunch of name comparisons even if they might not be needed.

We should at least make catch blocks `cleanup=False`, and we should probably implement the catch clauses appropriately. This requires support from the personality function to check for the match condition according to [some presentation slides](https://llvm.org/devmtg/2011-09-16/EuroLLVM2011-ExceptionHandling.pdf). We should also add a resume instruction if no exception clause is matched, according to the slides and code emitted from clang.

I am unsure about the performance implication of this and if my understanding of this is correct. I will try to fix this and give a simple microbenchmark.

**Comment by pca006132** [comment]
In addition to this, according to the comments, the name should be a unique global pointer for each type. If so, can we speed up the comparison by only doing a pointer comparison instead of `memcmp` of the whole string?

**Comment by pca006132** [comment]
Furthermore, the following code would trigger compiler exception:

```python
class UseError(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        try:
            pass
        except RTIOUnderflow as e:
            pass
```

Error:
```
Traceback (most recent call last):
  File "/nix/store/2bysrswbkq98hkmg9n66qy36azifqfbf-python3.8-artiq-7.7907.bbac4770.beta/bin/.artiq_run-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 224, in main
    return run(with_file=True)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 210, in run
    raise exn
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 203, in run
    exp_inst.run()
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/coredevice/core.py", line 131, in run
    self.compile(function, args, kwargs, set_result)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/coredevice/core.py", line 109, in compile
    module = Module(stitcher,
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/module.py", line 79, in __init__
    dead_code_eliminator.process(self.artiq_ir)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/transforms/dead_code_eliminator.py", line 15, in process
    self.process_function(func)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/transforms/dead_code_eliminator.py", line 23, in process_function
    self.remove_block(block)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/transforms/dead_code_eliminator.py", line 55, in remove_block
    block.erase()
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/ir.py", line 369, in erase
    insn.erase()
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/ir.py", line 238, in erase
    assert not any(self.uses)
AssertionError
```

And the following code will produce incorrect LLVM IR:
```python
class BlinkForever(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        try:
            if True:
                raise RTIOUnderflow()
        except RTIOUnderflow as e:
            raise e
        finally:
            pass
```
Error:
```
Traceback (most recent call last):
  File "/nix/store/2bysrswbkq98hkmg9n66qy36azifqfbf-python3.8-artiq-7.7907.bbac4770.beta/bin/.artiq_run-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 224, in main
    return run(with_file=True)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 210, in run
    raise exn
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/frontend/artiq_run.py", line 203, in run
    exp_inst.run()
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/coredevice/core.py", line 131, in run
    self.compile(function, args, kwargs, set_result)
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/coredevice/core.py", line 114, in compile
    library = target.compile_and_link([module])
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/targets.py", line 199, in compile_and_link
    return self.link([self.assemble(self.compile(module)) for module in modules])
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/targets.py", line 199, in <listcomp>
    return self.link([self.assemble(self.compile(module)) for module in modules])
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/artiq/compiler/targets.py", line 155, in compile
    llparsedmod.verify()
  File "/nix/store/1mj85w5mv07yf423fmr1bddww8wrvir3-python3-3.8.11-env/lib/python3.8/site-packages/llvmlite/binding/module.py", line 115, in verify
    raise RuntimeError(str(outmsg))
RuntimeError: Instruction does not dominate all uses!
  %.12 = bitcast i8* %.11 to %C.Exception.11*
  %UNN.18 = getelementptr inbounds %C.Exception.11, %C.Exception.11* %.12, i32 0, i32 1
Instruction does not dominate all uses!
  %.12 = bitcast i8* %.11 to %C.Exception.11*
  %UNN.19 = getelementptr inbounds %C.Exception.11, %C.Exception.11* %.12, i32 0, i32 2
Instruction does not dominate all uses!
  %.12 = bitcast i8* %.11 to %C.Exception.11*
  %UNN.20 = getelementptr inbounds %C.Exception.11, %C.Exception.11* %.12, i32 0, i32 3
Instruction does not dominate all uses!
  %.12 = bitcast i8* %.11 to %C.Exception.11*
  %UNN.21 = getelementptr inbounds %C.Exception.11, %C.Exception.11* %.12, i32 0, i32 4
Instruction does not dominate all uses!
  %.12 = bitcast i8* %.11 to %C.Exception.11*
  call void @__artiq_raise(%C.Exception.11* %.12) #2
```

**Comment by pca006132** [comment]
https://git.m-labs.hk/M-Labs/artiq-zynq/pulls/161

Addresses the landing pad issue.

**Comment by pca006132** [comment]
There are two problems with the IR generation and dead code elimination. The first problem is due to dead code elimination, landingpad clauses are not removed properly, a simple fix would do:
```diff
diff --git a/artiq/compiler/ir.py b/artiq/compiler/ir.py
index ae786f8a..92bc4fb3 100644
--- a/artiq/compiler/ir.py
+++ b/artiq/compiler/ir.py
@@ -1360,6 +1360,14 @@ class LandingPad(Terminator):
     def cleanup(self):
         return self.operands[0]
 
+    def erase(self):
+        self.remove_from_parent()
+        # we should erase all clauses as well
+        for block in set(self.operands):
+            block.uses.remove(self)
+            block.erase()
+        assert not any(self.uses)
+
     def clauses(self):
         return zip(self.operands[1:], self.types)
```

However, the second issue is a bit more complicated. Firstly, our deadcode eliminator cannot trace indirectbranch especially when the location is set in a local (not sure if phi could work), so some cases will trigger assertion errors due to invalid erases. Secondly, LLVM cannot reason about such control flow and will complain about instruction does not dominate all uses. Consider the simple example:
```
    @kernel
    def run(self):
        try:
            self.foo() # foo can be anything
        except RTIOUnderflow as e:
            raise e
        finally:
            pass
```

The IR output is something like this:
```
NoneType _Z40artiq_run_blink_forever.BlinkForever.runzz(environment(...) %ARG.ENV, <instance artiq_run_blink_forever.BlinkForever> %ARG.self) { ; type: (self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType
entry: ; predecessors: 
; blink_forever.py:15     def run(self):
  %ENV = environment($outer=environment, e=artiq.coredevice.exceptions.RTIOUnderflow, self=<instance artiq_run_blink_forever.BlinkForever>) alloc
  %PRV = environment($return=NoneType) alloc
  setlocal('$outer') %ENV, environment(...) %ARG.ENV
  setlocal('self') %ENV, <instance artiq_run_blink_forever.BlinkForever> %ARG.self
; blink_forever.py:16         try:
  %UNN.3 = environment($cont=label) alloc
  branch label %try.body
try.body: ; predecessors: entry
; blink_forever.py:17             self.foo()
  %LOC.self.FLD.foo = method(fn=(self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType, self=<instance artiq_run_blink_forever.BlinkForever>) getattr('foo') <instance artiq_run_blink_forever.BlinkForever> %ARG.self
; blink_forever.py:17             self.foo()
  %LOC.self.FLD.foo.ENV = (self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType getattr('__func__') method(fn=(self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType, self=<instance artiq_run_blink_forever.BlinkForever>) %LOC.self.FLD.foo
  %LOC.self.FLD.foo.SLF = <instance artiq_run_blink_forever.BlinkForever> getattr('__self__') method(fn=(self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType, self=<instance artiq_run_blink_forever.BlinkForever>) %LOC.self.FLD.foo
  invoke (self:<instance artiq_run_blink_forever.BlinkForever>)->NoneType %LOC.self.FLD.foo.ENV, <instance artiq_run_blink_forever.BlinkForever> %LOC.self.FLD.foo.SLF to label %invoke unwind label %try.dispatch
try.dispatch: ; predecessors: try.body
  %UNN.9 = Exception landingpad cleanup label %handler.cleanup, [artiq.coredevice.exceptions.RTIOUnderflow => label %handler.artiq.coredevice.exceptions.RTIOUnderflow]
handler.artiq.coredevice.exceptions.RTIOUnderflow: ; predecessors: try.dispatch
; blink_forever.py:16         try:
  %BLT.exncast = artiq.coredevice.exceptions.RTIOUnderflow builtin(exncast) Exception %UNN.9
  setlocal('e') %ENV, artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast
; <synthesized>
  setlocal('$cont') %UNN.3, label %try.raise
  branch label %finally
handler.cleanup: ; predecessors: try.dispatch
  branch label %finally.reraise
finally.reraise: ; predecessors: handler.cleanup
; blink_forever.py:21             pass
  builtin(nop)
; blink_forever.py:16         try:
  reraise
invoke: ; predecessors: try.body
  setlocal('$cont') %UNN.3, label %try.tail
  branch label %finally
finally: ; predecessors: handler.artiq.coredevice.exceptions.RTIOUnderflow, invoke
; blink_forever.py:21             pass
  builtin(nop)
; <synthesized>
  %UNN.24 = label getlocal('$cont') %UNN.3
  indirectbranch label %UNN.24, [label %try.doreturn, label %try.raise, label %try.tail]
try.tail: ; predecessors: finally
  return NoneType None
try.raise: ; predecessors: finally
; blink_forever.py:19             raise e
  setattr('__file__') artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast, str 'blink_forever.py'
  setattr('__line__') artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast, numpy.int32 19
  setattr('__col__') artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast, numpy.int32 12
  setattr('__func__') artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast, str '_Z40artiq_run_blink_forever.BlinkForever.runzz'
  raise artiq.coredevice.exceptions.RTIOUnderflow %BLT.exncast
try.doreturn: ; predecessors: finally
  %UNN.4 = NoneType getlocal('$return') %PRV
  return NoneType %UNN.4
}
```

Basically, what it is doing is:
```
%entry:
    call self.foo(), if unwind go to %landingpad, otherwise goto %invoke
%invoke:
    set $cont = %try.tail
    goto %finally
%landingpad:
    // ignoring various clauses
    cast the exception into our object type
    set $cont = %try.raise
    goto %finally
%finally:
    // do nothing, as we put a pass there
    indirectbr $cont // this is the core reason
%try.tail:
    return
%try.raise:
    raise exception
```
However, LLVM cannot understand that `%try.raise` is dominated by `%landingpad`, because the predecessor of `%try.raise` is `%finally`, which has two predecessors `%invoke` and `%landingpad` even though the path through `%invoke` is impossible.

It seems that the only way to fix this issue is to modify the IR generation and duplicate the finally block. I am not sure if there are better ways for this.
