### ISSUE TITLE
Underflows don't generate proper tracebacks

### ISSUE THREAD

**Issue by hartytp** [m-labs/artiq#1821]
# Bug Report

## One-Line Summary

Underflows don't generate proper tracebacks using the latest master.

### Steps to Reproduce

```python
from artiq.language import *

class TestBacktrace(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl0")

    @kernel
    def run(self):
        at_mu(0)
        self.ttl0.on()
```

### Expected Behavior

A traceback pointing to the line in the source with `self.ttl0.on()`.

### Actual (undesired) Behavior

```
root:Terminating with exception (RTIOUnderflow: RTIO underflow at 1998784798638454 mu, channel 131091, slack -5274 mu)
Core Device Traceback (most recent call last):
  File "ksupport/rtio.rs", line 69, column 14, in (Rust function)
    <unknown>
```

### Your System (omit irrelevant parts)

Latest master (thanks to @sbourdeauducq for reproducing at M-Labs).

**Comment by occheung** [comment]
Fixed after 6f3c495 & 5e1847e.
The line of code that causes underflow can now be seen on the traceback.
```
WARNING:artiq.coredevice.comm_kernel:Mismatch between gateware (7.unknown.beta) and software (7.0-dev) versions
Core Device Traceback (most recent call last):
  File "backtrace_test.py", line 11, in artiq_run_backtrace_test.TestBacktrace.run(..., ...) (RA=+0x120)
    self.led0.on()
  File "<artiq>/coredevice/ttl.py", line 53, in ... artiq.coredevice.ttl.TTLOut.on<artiq.coredevice.ttl.TTLOut>(...) (inlined)
    self.set_o(True)
  File "<artiq>/coredevice/ttl.py", line 45, in ... artiq.coredevice.ttl.TTLOut.set_o<artiq.coredevice.ttl.TTLOut>(...) (inlined)
    rtio_output(self.target_o, 1 if o else 0)
  File "ksupport/rtio.rs", line 69, column 14, in (Rust function)
    <unknown>
                 ^
artiq.coredevice.exceptions.RTIOUnderflow(0): RTIO underflow at 4404489616454 mu, channel 13, slack -3434 mu
Traceback (most recent call last):
  File "/nix/store/3swvambv2pa63fwjggcd76glqqsvcjj7-python3.9-artiq-7.0-dev/bin/.artiq_run-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/frontend/artiq_run.py", line 224, in main
    return run(with_file=True)
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/frontend/artiq_run.py", line 210, in run
    raise exn
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/frontend/artiq_run.py", line 203, in run
    exp_inst.run()
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/coredevice/core.py", line 139, in run
    self.comm.serve(embedding_map, symbolizer, demangler)
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/coredevice/comm_kernel.py", line 655, in serve
    self._serve_exception(embedding_map, symbolizer, demangler)
  File "/nix/store/1wbgw3b7zc7652zv121fqkyy4h9q1cgg-python3-3.9.6-env/lib/python3.9/site-packages/artiq/coredevice/comm_kernel.py", line 637, in _serve_exception
    raise python_exn
artiq.coredevice.exceptions.RTIOUnderflow: RTIO underflow at 4404489616454 mu, channel 13, slack -3434 mu
```
