### ISSUE TITLE
ARTIQ installation issues with Windows/Conda

### ISSUE THREAD

**Issue by SaivaHuck** [m-labs/artiq#1977]
# Bug Report

## One-Line Summary

Impossible to install ARTIQ7 in a fully functional way on Windows/Conda

### Steps to Reproduce

1. Try installing ARTIQ7 using Conda on Windows (following the steps on https://m-labs.hk/artiq/manual/installing.html#installing-via-conda-windows-linux as has always worked)
2. Get the errors from the attached picture 
![ARTIQ_installation_error](https://user-images.githubusercontent.com/80470537/196117547-d192be68-eae8-4498-8ed7-ab81656ceccd.jpeg)
3. Delete the concerned files manually, redo the installation and get the same error
4. Try the installation using an elevated shell (admin rights) -> the installation works
5. Running certain routines works, for others you get an error ("core device quit unexpectedly"), while these same routines have always worked and still do on computers with an older installation of ARTIQ7

### Expected Behavior

Running routines normally after installing current ARTIQ7 version

### Actual (undesired) Behavior

Getting "core device quit unexpectedly" errors for certain routines (see attachment below, TestAlex.py works while Kasli_1TC1_PsCooling_simple does not work - they access the same class libraries and overall structure)
[Kasli_1TC1_TestAlex.txt](https://github.com/m-labs/artiq/files/9798055/Kasli_1TC1_TestAlex.txt)
[Kasli_1TC1_PsCooling_simple.txt](https://github.com/m-labs/artiq/files/9798058/Kasli_1TC1_PsCooling_simple.txt)

### Your System (omit irrelevant parts)

* Operating System:
* ARTIQ version: 7.8123.3038639
* Version of the gateware and runtime loaded in the core device: 
[coremgmt_log_output.docx](https://github.com/m-labs/artiq/files/9798078/coremgmt_log_output.docx)

* If using Conda, output of `conda list` (please submit as a file attachment, as this tends to be long) 
[conda list output.txt](https://github.com/m-labs/artiq/files/9798115/conda.list.output.txt)

* Hardware involved: Kasli 2.0 - we also have MCX DIO units and Fastinos, but this is probably irrelevant

**Comment by SaivaHuck** [comment]
Thank you for your quick reply.

Yes, I was expecting this, obviously we're trying to narrow the problem down. However, we are in the middle of a very time-restricted data taking period and don't have the time to debug this in detail. I wanted to go ahead and post this issue in case somebody already knew the clear solution since we of course desperately need this to work. Apologies.
We will of course work on this.

Please find below the terminal output with the errors:

(artiq) C:\kasli-code\Scripts\1T_upgraded>artiq_run Kasli_1TC1_PsCooling_simple.py
Configuring for 1T operation ...
WARNING:artiq.coredevice.comm_kernel:Mismatch between gateware (7.8019.f89275b.beta) and software (7.8123.3038639) versions
Traceback (most recent call last):
  File "C:\Users\aegis\anaconda3\envs\artiq\Scripts\artiq_run-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 224, in main
    return run(with_file=True)
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 210, in run
    raise exn
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\frontend\artiq_run.py", line 203, in run
    exp_inst.run()
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\language\core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\core.py", line 140, in run
    self._run_compiled(kernel_library, embedding_map, symbolizer, demangler)
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\core.py", line 130, in _run_compiled
    self.comm.serve(embedding_map, symbolizer, demangler)
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\comm_kernel.py", line 706, in serve
    self._read_header()
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\comm_kernel.py", line 249, in _read_header
    sync_byte = self._read(1)[0]
  File "C:\Users\aegis\anaconda3\envs\artiq\lib\site-packages\artiq\coredevice\comm_kernel.py", line 237, in _read
    raise ConnectionResetError("Core device connection closed unexpectedly")
ConnectionResetError: Core device connection closed unexpectedly


I've also attached the coremgmt_log_output as .txt file.
[coremgmt_log_output.txt](https://github.com/m-labs/artiq/files/9799195/coremgmt_log_output.txt)


Please let us know if you have an idea for a workaround, and we will try to narrow down/pin point the code that is actually the problem.
Thank you!!

**Comment by SaivaHuck** [comment]
We're definitely not running two kernels in parallel on purpose. If that is happening, there's probably something wrong.

Is that what is causing this error? Because we are only getting this exact error when running from the newly installed ARTIQ7 version (on several different host machines) and with none of the others (on several different host machines).
