### ISSUE TITLE
Browser fails to read the metadata from HDF5 files

### ISSUE THREAD

**Issue by thomasfire** [m-labs/artiq#2012]
# Bug Report

## One-Line Summary

Browser fails to read the metadata from HDF5 files

### Steps to Reproduce

1. Run experiment via artiq_dashboard or artiq_run with HDF5 option,
2. open artiq_browser,
3. in the files view, navigate to the newly created HDF5 file,
4. click on the file to see metadata.

### Expected Behavior

Datasets pane shows file's metadata, or at least indicates that some fields are missing (?).

### Actual (undesired) Behavior

```py
WARNING:browser:artiq.browser.files:unable to read metadata from /home/esavkin/artiq/results/2022-12-01/09/000000027-BadString.h5
Traceback (most recent call last):
  File "/nix/store/1ns6470n83df88q9c1abwdinnkanf4mp-python3-3.10.8-env/lib/python3.10/site-packages/artiq/browser/files.py", line 181, in list_current_changed
    "repo_rev": expid["repo_rev"],
KeyError: 'repo_rev'
```

**Comment by thomasfire** [comment]
> Did you actually try to do that or are you just guessing? 

Just tried:
```sh
$ artiq_master &
$ artiq_client submit repository/bad_string.py
$ artiq_browser
... (choosing recent file)
WARNING:browser:artiq.browser.files:unable to read metadata from /home/esavkin/artiq/results/2022-12-02/10/000000031-BadString.h5
Traceback (most recent call last):
  File "/nix/store/s0v77iisbxb0rh08vfnj5w4w8qx7sqsm-python3-3.10.8-env/lib/python3.10/site-packages/artiq/browser/files.py", line 181, in list_current_changed
    "repo_rev": expid["repo_rev"],
KeyError: 'repo_rev'
```
