### ISSUE TITLE
Virtual device scheduler fails to submit kernel code

### ISSUE THREAD

**Issue by thomasfire** [m-labs/artiq#2021]
# Bug Report

## One-Line Summary

Vrtual device scheduler fails to run kernel code. https://forum.m-labs.hk/d/530-submit-experiments-using-virtual-device-scheduler

### Steps to Reproduce

1. `schedule_test.py`:
```py
from artiq.experiment import *

class ScheduleTest(EnvExperiment):
    def build(self):
        self._scheduler = self.get_device("scheduler")

    def run(self):
        new_expid = {
            "file": "repository/test.py",
            "class_name": "Test",
            "arguments": {},
            "log_level": 30,
        }

        self._scheduler.submit(pipeline_name="main", expid=new_expid)
```
2. `repository/test.py`:
```py
from artiq.experiment import *


class Test(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    def run(self):
        print("test")
        self._run()

    @kernel
    def _run(self):
        print("test from kernel")
```
3. `artiq_master &`
4. `artiq_client submit schedule_test.py`

### Expected Behavior

Experiment runs without errors and prints both `test` and `test from kernel`.

### Actual (undesired) Behavior

```py
INFO:worker(55,test.py):print:test
ERROR:worker(55,test.py):root:Terminating with exception (OSError: source code not available)
Traceback (most recent call last):
  File "/home/esavkin/artiq/artiq/master/worker_impl.py", line 343, in main
    exp_inst.run()
  File "repository/test.py", line 10, in run
    self._run()
  File "/home/esavkin/artiq/artiq/language/core.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/home/esavkin/artiq/artiq/coredevice/core.py", line 139, in run
    self.compile(function, args, kwargs, set_result)
  File "/home/esavkin/artiq/artiq/coredevice/core.py", line 107, in compile
    stitcher.stitch_call(function, args, kwargs, set_result)
  File "/home/esavkin/artiq/artiq/compiler/embedding.py", line 777, in stitch_call
    call_node = synthesizer.call(function, args, kwargs, callback)
  File "/home/esavkin/artiq/artiq/compiler/embedding.py", line 448, in call
    callee_node = self.quote(callee)
  File "/home/esavkin/artiq/artiq/compiler/embedding.py", line 342, in quote
    function_type = self.quote_function(value, self.expanded_from)
  File "/home/esavkin/artiq/artiq/compiler/embedding.py", line 1208, in _quote_function
    self._quote_embedded_function(function,
  File "/home/esavkin/artiq/artiq/compiler/embedding.py", line 955, in _quote_embedded_function
    source_code = inspect.getsource(embedded_function)
  File "/nix/store/x9na3pxf7134pq7dkn1kgy9df6lf1z4v-python3-3.9.13/lib/python3.9/inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "/nix/store/x9na3pxf7134pq7dkn1kgy9df6lf1z4v-python3-3.9.13/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/nix/store/x9na3pxf7134pq7dkn1kgy9df6lf1z4v-python3-3.9.13/lib/python3.9/inspect.py", line 827, in findsource
    raise OSError('source code not available')
OSError: source code not available
ERROR:master:artiq.master.scheduler:got worker exception in run stage, deleting RID 55
```

**Comment by thomasfire** [comment]
Appears that it fails to locate the source with the  relative path used. Absolute path works normally.
