### ISSUE TITLE
conda fails to install artiq-kc705-nist_qc1

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#222]
```
$ conda install   artiq-kc705-nist_qc1
Fetching package metadata: ........
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/py35dev/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 403, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 747, in solve
    minimal_hint=minimal_hint)
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 492, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/rabi/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 350, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: artiq-0.0-py_2399+git63f7899.tar.bz2 MatchSpec('aiohttp')
```

**Comment by sbourdeauducq** [comment]
That works with a fresh Anaconda 2.4.1 installation. @jboulder please reopen if for some reason you want to keep using the old broken one you have.
