### ISSUE TITLE
Conda installation on windows couldn't find artiq

### ISSUE THREAD

**Issue by thomasfire** [m-labs/artiq#2398]
# Bug Report

## One-Line Summary

Conda installation on windows couldn't find artiq. 

## Issue Details

Probably related to the Python 3.12 being pushed in conda. 

```shell
(base) PS C:\Users\esmlabs> conda activate artiq
(artiq) PS C:\Users\esmlabs> artiq_browser
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\artiq\Scripts\artiq_browser-script.py", line 5, in <module>
    from artiq.frontend.artiq_browser import main
ModuleNotFoundError: No module named 'artiq'
(artiq) PS C:\Users\esmlabs> artiq_run
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\artiq\Scripts\artiq_run-script.py", line 5, in <module>
    from artiq.frontend.artiq_run import main
ModuleNotFoundError: No module named 'artiq'
```

### Steps to Reproduce

1. Clean install windows 11/10
2. Follow official instructions for conda installation on windows (both release-7 and beta), either miniconda or full anaconda
3. In artiq environment, try run any artiq command
4. Any command fails with `ModuleNotFoundError: No module named 'artiq'`

### Your System (omit irrelevant parts)

* Operating System: Windows 11/10, Fedora 40
* ARTIQ version: release-7 and master
* Hardware involved: QEMU VM

**Comment by thatschatt** [comment]
I was seeing problems where the artiq packages were installed into env/artiq/site-packages instead of env/artiq/Lib/site-packages , however I just tried again, and this time they ended up in the right place. So maybe fixed?

**Comment by thomasfire** [comment]
> I was seeing problems where the artiq packages were installed into env/artiq/site-packages instead of env/artiq/Lib/site-packages

I checked it now, and it indeed seems to be the case
