### ISSUE TITLE
spurious exceptions on server side when clients disconnects on Windows

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#247]
On Windows, there are some exceptions (ConnectionAbortedError, ConnectionResetError, ...) that appear in more situations than Linux and are not properly caught.

**Comment by sbourdeauducq** [comment]
I have fixed those I found in ARTIQ. The last common one seems to be a bug in asyncio:
```
ERROR:master:asyncio:Fatal write error on pipe transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x0000000003F63FD0>
transport: <_ProactorSocketTransport fd=756>
Traceback (most recent call last):
  File "C:\Users\User\Miniconda3\lib\asyncio\proactor_events.py", line 283, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Users\User\Miniconda3\lib\asyncio\windows_events.py", line 450, in send
    ov.WSASend(conn.fileno(), buf, flags)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software on your host machine.
```

**Comment by sbourdeauducq** [comment]
https://github.com/python/asyncio/issues/319
