### ISSUE TITLE
Question on Arguments Pass to Experiments and/or How to Debug

### ISSUE THREAD

**Issue by pyquest1** [m-labs/artiq#2608]
Hi All,

I am trying to setup some low-level experiments to be called by later/higher level experiments.  Towards that end I am trying to understand how to flexibly control the experiments I am creating.

As a basic example - consider trying to dynamically reconfigure the which channels of a DAC or ADC are in use and at what sampling rate.

Basic- Example - try to pass "which channels to measure from on the Sampler".

`rom artiq.experiment import *                      #imports everything from experiment library
import numpy as np                                  #imports everything from numpy library

# This code takes 2000 samples from all 8 channels and saves the samples from channel 0 to a dataset called samples
# An applet can be written in the management system to plot the data from this dataset
# Alternatively, the H5 file can be opened using HDFview and can then be plotted

class Sampler_Base_Class(EnvExperiment):
    """Sampler Base Code"""

    def build(self,channel): #this code runs on the host device
        super().build()
        self.setattr_device("core")                 #saves core device drivers as attributes
        self.setattr_device("sampler0")             #saves sampler device drivers as attributes
        self.channel = channel

    @kernel #this code is run on the FPGA
    def run(self):
         self.core.reset()                                                               #resets core device

         self.core.break_realtime()                                                      #Time break to avoid underflow condition
         self.sampler0.init()                                                            #initialises sampler
        
         n_samples = 20      
         #n_channels = 8                                     #sets number of channels to read off of
                                                             #defines number of samples to be taken

         channel_strings = ['Sample_Ch0','Sample_Ch1','Sample_Ch2','Sample_Ch3','Sample_Ch4',
         'Sample_Ch5','Sample_Ch6','Sample_Ch7']

         channels = [1,2,3]
         for i in channels:   
             strings = channel_strings[i] 
             self.set_dataset(strings, np.full(n_samples, np.nan), broadcast=True)
             delay(100*us)                   
             print(strings)                      `

However, this leads to an error

`
artiq_run Sampler_Base.py channel =[1]
Traceback (most recent call last):
  File "/nix/store/m4sad7hvxxjyizy3brykn4wk49mn3sdc-python3.11-artiq-8.8956+f6cf893/bin/.artiq_run-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/artiq/frontend/artiq_run.py", line 269, in main
    return run(with_file=True)
           ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/artiq/frontend/artiq_run.py", line 253, in run
    raise exn
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/artiq/frontend/artiq_run.py", line 243, in run
    exp_inst = _build_experiment(device_mgr, dataset_mgr, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/artiq/frontend/artiq_run.py", line 191, in _build_experiment
    arguments = parse_arguments(args.arguments)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/artiq/tools.py", line 37, in parse_arguments
    d[name] = pyon.decode(value)
              ^^^^^^^^^^^^^^^^^^
  File "/nix/store/xr6dmqbnyspg6vla94ym3vrl5ax3k037-python3-3.11.9-env/lib/python3.11/site-packages/sipyco/pyon.py", line 218, in decode
    return eval(s, _eval_dict, {})
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 0
    
SyntaxError: invalid syntax

`

**Comment by SimonRenblad** [comment]
You need to call `self.setattr_argument` in your build method. Then you can use `artiq_run`, `artiq_client` or `artiq_dashboard` to schedule and run your experiment. I'd recommend looking at the `arguments_demo.py` example in the `no_hardware` folder. Manual: https://m-labs.hk/artiq/manual/getting_started_mgmt.html#adding-arguments.
