### ISSUE TITLE
artiq_rpctool --target not working

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#283]
Seems to always choose `AutoTarget` and then complains. Or am I doing something wrong here:

```
(py35)rj@tito:~/work/nist/artiq/run (master)$ artiq_rpctool localhost 3251 list-targets
Target(s):   master_dataset_db, master_device_db, master_experiment_db, master_schedule
(py35)rj@tito:~/work/nist/artiq/run (master)$ artiq_rpctool localhost 3251 list-methods -h
usage: artiq_rpctool server port list-methods [-h] [-t TARGET]

optional arguments:
  -h, --help            show this help message and exit
  -t TARGET, --target TARGET
                        target name
(py35)rj@tito:~/work/nist/artiq/run (master)$ artiq_rpctool localhost 3251 list-methods -t master_device_db
Traceback (most recent call last):
  File "/home/rj/src/conda/envs/py35/bin/artiq_rpctool", line 9, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_rpctool')()
  File "/home/rj/work/nist/artiq/artiq/frontend/artiq_rpctool.py", line 90, in main
    remote.select_rpc_target(AutoTarget)
  File "/home/rj/work/nist/artiq/artiq/protocols/pc_rpc.py", line 120, in select_rpc_target
    target_name = _validate_target_name(target_name, self.__target_names)
  File "/home/rj/work/nist/artiq/artiq/protocols/pc_rpc.py", line 55, in _validate_target_name
    " ".join(sorted(target_names)))
ValueError: Server has multiple targets: master_dataset_db master_device_db master_experiment_db master_schedule
(py35)rj@tito:~/work/nist/artiq/run (master)$
```

**Comment by sbourdeauducq** [comment]
``-t/--target`` must come before the subparser (list-targets,list-methods,call) names. This seems to be a ``argparse`` problem that it doesn't complain about this command line.
