### ISSUE TITLE
mandelbrot example breaks connection + corelog

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#300]
```
$ artiq_run.py repository/coredevice_examples/simple/mandelb
WARNING:artiq.coredevice.comm_generic:Mismatch between gateware (0.1+954.g0395119) and software (0.1+984.g485fc3b.dirty) versions
               ...............................................................
             .....................,,,,,,,,,,,.................................
            .............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,........................
          ..........,,,,,,,,,,,,,,,,,,,,,,,----------,,,,,,...................
         ........,,,,,,,,,,,,,,,,,,,,,------::;h+;::-----,,,,,................
       .......,,,,,,,,,,,,,,,,,,,,,--------:::;+MMhM :------,,,,,.............
      .....,,,,,,,,,,,,,,,,,,,,,---------::::ii+M $hi;::------,,,,,,..........
     ....,,,,,,,,,,,,,,,,,,,,,---------:::;;h      * +;::::----,,,,,,,........
    ....,,,,,,,,,,,,,,,,,,,---------::;;;;ii+$      @hi;;:::::---,,,,,,.......
    ..,,,,,,,,,,,,,,,,,,,-------:::;h+Mh++HHH$      *Hhh+i;;ihi:--,,,,,,,.....
   ..,,,,,,,,,,,,,,,,,------:::::;;i     #               HH M*M+:--,,,,,,,....
  ..,,,,,,,,,,,,,,,,---::::::::;;;i+h#                        h;::-,,,,,,,,...
  .,,,,,,,,,,,,,---:;;::::::;;;;i+                           M+i;:--,,,,,,,,..
 .,,,,,,,,-----::;;M+iiiih+iiii++h                             M :---,,,,,,,,.
 .,,,--------::::;i+$   M# $ HhhH$                             $i;---,,,,,,,,.
 ,,--------:::::;iihM          **                               i:----,,,,,,,,
 ,-------::::;; +hH*                                           h;:----,,,,,,,,
 -:::-:;;;;;ii+h                                              +;::----,,,,,,,,
                                                            Mhi;::----,,,,,,,,
 -:::-:;;;;;ii+h                                              +;::----,,,,,,,,
 ,-------::::;; +hH*                                           h;:----,,,,,,,,
 ,,--------:::::;iihM          **                               i:----,,,,,,,,
 .,,,--------::::;i+$   M# $ HhhH$                             $i;---,,,,,,,,.
 .,,,,,,,,-----::;;M+iiiih+iiii++h                             M :---,,,,,,,,.
  .,,,,,,,,,,,,,---:;;::::::;;;;i+                           M+i;:--,,,,,,,,..
  ..,,,,,,,,,,,,,,,,---::::::::;;;i+h#                        h;::-,,,,,,,,...
   ..,,,,,,,,,,,,,,,,,------:::::;;i     #               HH M*M+:--,,,,,,,....
    ..,,,,,,,,,,,,,,,,,,,-------:::;h+Mh++HHH$      *Hhh+i;;ihi:--,,,,,,,.....
    ....,,,,,,,,,,,,,,,,,,,---------::;;;;ii+$      @hi;;:::::---,,,,,,.......
     ....,,,,,,,,,,,,,,,,,,,,,---------:::;;h      * +;::::----,,,,,,,........
      .....,,,,,,,,,,,,,,,,,,,,,---------::::ii+M $hi;::------,,,,,,..........
       .......,,,,,,,,,,,,,,,,,,,,,--------:::;+MMhM :------,,,,,.............
         ........,,,,,,,,,,,,,,,,,,,,,------::;h+;::-----,,,,,................
          ..........,,,,,,,,,,,,,,,,,,,,,,,----------,,,,,,...................
            .............,,,,,,,,,,,,,,,,,,,,,,,,,,,,,........................
             .....................,,,,,,,,,,,.................................
Traceback (most recent call last):
  File "/home/sb/artiq/artiq/frontend/artiq_run.py", line 203, in <module>
    main()
  File "/home/sb/artiq/artiq/frontend/artiq_run.py", line 199, in main
    return run(with_file=True)
  File "/home/sb/artiq/artiq/frontend/artiq_run.py", line 185, in run
    raise exn
  File "/home/sb/artiq/artiq/frontend/artiq_run.py", line 178, in run
    exp_inst.run()
  File "/home/sb/artiq/artiq/language/core.py", line 192, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/home/sb/artiq/artiq/coredevice/core.py", line 108, in run
    self.comm.serve(object_map, symbolizer)
  File "/home/sb/artiq/artiq/coredevice/comm_generic.py", line 520, in serve
    self._read_header()
  File "/home/sb/artiq/artiq/coredevice/comm_generic.py", line 101, in _read_header
    (sync_byte, ) = struct.unpack("B", self.read(1))
  File "/home/sb/artiq/artiq/coredevice/comm_tcp.py", line 60, in read
    raise IOError("Connection closed")
OSError: Connection closed

$ artiq_corelog.py 
WARNING:artiq.coredevice.comm_generic:Mismatch between gateware (0.1+954.g0395119) and software (0.1+984.g485fc3b.dirty) versions
Traceback (most recent call last):
  File "/home/sb/artiq/artiq/frontend/artiq_corelog.py", line 32, in <module>
    main()
  File "/home/sb/artiq/artiq/frontend/artiq_corelog.py", line 26, in main
    print(comm.get_log(), end="")
  File "/home/sb/artiq/artiq/coredevice/comm_generic.py", line 245, in get_log
    return self._read_chunk(self._read_length).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 3736: invalid start byte

```

```
$ flterm --port /dev/ttyUSB0
[FLTERM] Starting...
send_rpc_value: unknown tag ffffffff
Failed to send RPC request (service 0, tag ����������������������������)
```

**Comment by sbourdeauducq** [comment]
Problem fixed after upgrading runtime, ``artiq_corelog`` should nevertheless not fail in this way when receiving something that isn't correct Unicode, and should instead attempt to display something.
