### ISSUE TITLE
Error with histograms.py

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#459]
I was trying to run  artiq/artiq/examples/master/repository/histograms.py on 1.0 on Windows.

It seems like it needs a build function if not it doesn't load in the repository due to a `NotImplementedError`.

Also, I think the set datasets need to be after the for loop,

```python
        for i in range(npoints):
            histogram, _ = np.histogram(np.random.normal(i, size=1000),
                                        bin_boundaries)
            counts[i] = histogram
            xs[i] = i % 8
            sleep(0.3)
            
        self.set_dataset("hd_xs", xs,
                              broadcast=True, save=False)
        self.set_dataset("hd_counts", counts, 
                              broadcast=True, save=False)
```

If not you get errors like this,

```
ERROR:worker(11691,histogram_test.py):root:Terminating with exception (TypeError
: 'NoneType' object does not support item assignment)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-0524\lib\site-packages\artiq\master\worker_impl.
py", line 226, in main
    exp_inst.run()
  File "C:\artiq-magtrap\repository\test\histogram_test.py", line 40, in run
    counts[i] = histogram
TypeError: 'NoneType' object does not support item assignment
ERROR:master:artiq.master.scheduler:got worker exception in run stage, deleting
RID 11691
ERROR:worker(11694,histogram_test.py):root:Terminating with exception (TypeError
: 'NoneType' object does not support item assignment)
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-0524\lib\site-packages\artiq\master\worker_impl.
py", line 226, in main
    exp_inst.run()
  File "C:\artiq-magtrap\repository\test\histogram_test.py", line 41, in run
    xs[i] = i % 8
TypeError: 'NoneType' object does not support item assignment
```

**Comment by sbourdeauducq** [comment]
> It seems like it needs a build function if not it doesn't load in the repository due to a NotImplementedError.

Please use the 1.0 version of the example with ARTIQ 1.0. Looking at the other problems now.
