### ISSUE TITLE
browser thumbnail breaks when HDF5 file is written in the currently displayed folder

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#470]
With this error displayed (Linux):
```
WARNING:browser:artiq.browser.files:unable to read HDF5 file /home/sb/artiq/artiq/examples/master/results/2016-06-08/13/000002378-Thumbnail.h5
Traceback (most recent call last):
  File "/home/sb/artiq/artiq/browser/files.py", line 18, in open_h5
    return h5py.File(info.filePath(), "r")
  File "/usr/lib/python3.5/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python3.5/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/python-h5py/src/h5py-2.6.0/h5py/_objects.c:2678)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/python-h5py/src/h5py-2.6.0/h5py/_objects.c:2636)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/build/python-h5py/src/h5py-2.6.0/h5py/h5f.c:1932)
OSError: Unable to open file (Unable to flock file, errno = 11, error message = 'resource temporarily unavailable')
```

**Comment by jordens** [comment]
That's a warning. We can suppress it (let's say on `OSError`) but an Icon needs to be returned (and is returned).
