### ISSUE TITLE
Closing GUI with an enabled applet that has an empty dataset prevents termination

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#475]
Using 1.0 on Windows. If I start the gui and enable 2 plot_xy applets with the default commands,

```
{python} -m artiq.applets.plot_xy --embed {ipc_address} Y_DATASET --x X_DATASET --error ERROR_DATASET --fit FIT_DATASET
```
And then try to close the GUI , the applet goes blank and some of the windows don't close, and the windows then say they're not responding.

![](http://s33.postimg.org/n58ksgfr3/gui_crash.png)

I then get a python is not responding notification. 

The artiq_gui traceback looks like this,
```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-2016-06-09\lib\site-packages\artiq\tools.py", li
ne 172, in <lambda>
    atexit.register(lambda: loop.run_until_complete(coroutine()))
  File "C:\Anaconda3\envs\artiq-2016-06-09\lib\site-packages\Quamash-0.5.5-py3.5
.egg\quamash\__init__.py", line 270, in run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

This seems to happen quite reliably as long as there are at least two applets open, at least one of which calling a dataset that is empty. This happened using the big number applet as well.

**Comment by sbourdeauducq** [comment]
```
DEBUG:dashboard:quamash.QEventLoop:Qt event loop ended with result 0
DEBUG:dashboard:quamash.QEventLoop:Callback timer fired, calling <Handle _wait.<locals>._on_completion(<Task finishe...> result=None>) at /usr/lib/python3.5/asyncio/tasks.py:408>
DEBUG:dashboard:quamash.QEventLoop:Registering callback <bound method Task._wakeup of <Task pending coro=<AppletsDock.stop() running at /home/sb/artiq/artiq/gui/applets.py:421> wait_for=<Future finished result=None>>> to be invoked with arguments (<Future finished result=None>,) after 0 second(s)
DEBUG:dashboard:quamash.QEventLoop:Adding callback <Handle Task._wakeup(<Future finished result=None>)> with delay 0
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/sb/artiq/artiq/tools.py", line 172, in <lambda>
    atexit.register(lambda: loop.run_until_complete(coroutine()))
  File "/usr/lib/python3.5/site-packages/quamash/__init__.py", line 247, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```
