### ISSUE TITLE
RPCReturnValueError: type mismatch: cannot serialize as 32-bit int

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#555]
Using 2.0.dev+563.gc4559fc on windows, I have the following code

```python
from artiq.experiment import *


def return_x(x) -> TInt32:
    print(type(x))
    return x


class RPC_Test(EnvExperiment):

    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        return_x(1)
```

Which generates the following error,

```
INFO:worker(20285,rpc_test.py):print:<class 'numpy.int32'>
ERROR:worker(20285,rpc_test.py):root:Terminating with exception (RPCReturnValueE
rror: type mismatch: cannot serialize 1 as 32-bit int (<function return_x at 0x0
000000004992510> has returned 1))
Core Device Traceback (most recent call last):
  File "C:\artiq-magtrap\repository\test/rpc_test.py", line 22, in __modinit__ (
RA=+0x3ec)
    return_x(1)
  File "<artiq>\coredevice\comm_generic.py", line 400, in _send_rpc_value
    lambda: "32-bit int")
artiq.coredevice.comm_generic.RPCReturnValueError(5): type mismatch: cannot seri
alize 1 as 32-bit int (<function return_x at 0x0000000004992510> has returned 1)

Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq-2016-08-31\lib\site-packages\artiq\master\worker
_impl.py", line 228, in main
    exp_inst.run()
  File "C:\Anaconda3\envs\artiq-2016-08-31\lib\site-packages\artiq\language\core
.py", line 54, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "C:\Anaconda3\envs\artiq-2016-08-31\lib\site-packages\artiq\coredevice\co
re.py", line 120, in run
    self.comm.serve(embedding_map, symbolizer, demangler)
  File "C:\Anaconda3\envs\artiq-2016-08-31\lib\site-packages\artiq\coredevice\co
mm_generic.py", line 537, in serve
    self._serve_exception(embedding_map, symbolizer, demangler)
  File "C:\Anaconda3\envs\artiq-2016-08-31\lib\site-packages\artiq\coredevice\co
mm_generic.py", line 529, in _serve_exception
    raise python_exn
artiq.coredevice.comm_generic.RPCReturnValueError: type mismatch: cannot seriali
ze 1 as 32-bit int (<function return_x at 0x0000000004992510> has returned 1)
ERROR:master:artiq.master.scheduler:got worker exception in run stage, deleting
RID 20285
```

How should I modify the function to return the value properly?

**Comment by whitequark** [comment]
@r-srinivas You don't need to. It was a bug.

**Comment by r-srinivas** [comment]
Thanks!
