### ISSUE TITLE
AttributeError: type object 'MiniSoC' has no attribute 'csr_map'

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#567]
I was trying to generate a bitstream for 2.0, following the instructions. I get the following error,

```
(artiq-2016-09-27) rabi@68810MAGTRAPVM:~/artiq-release-2$ python3.5 -m artiq.gateware.targets.kc705 -H nist_qc2
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-2016-09-27/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rabi/anaconda3/envs/artiq-2016-09-27/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rabi/anaconda3/envs/artiq-2016-09-27/lib/python3.5/site-packages/artiq/gateware/targets/kc705.py", line 103, in <module>
    class _NIST_Ions(MiniSoC, AMPSoC):
  File "/home/rabi/anaconda3/envs/artiq-2016-09-27/lib/python3.5/site-packages/artiq/gateware/targets/kc705.py", line 115, in _NIST_Ions
    csr_map.update(MiniSoC.csr_map)
AttributeError: type object 'MiniSoC' has no attribute 'csr_map'
```

 It seems like commit 
https://github.com/m-labs/misoc/commit/6af3e1b456876aaab85d4b40c7a2746e42d34d1d

changed how the csc_map is defined maybe and I see the master artiq/gateware/targets/kc705.py has been changed to update this but not the release-2 version. Checking out an earlier version of misoc seems to fix this. I'm wondering if the installation from source instructions should have instructions for how to install specific branches instead of just the master or if just updating the release-2 version of kc705.py is enough? Or possibly branching misoc and migen as well?

**Comment by sbourdeauducq** [comment]
#565
