### ISSUE TITLE
PYONValue default does not work for lists

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#682]
PYONValue does not handle list defaults:
```python
self.setattr_argument("test", PYONValue(default=[0,1,2,3]))
```
Gives the error:
```
root:Terminating with exception (NotImplementedError)
Traceback (most recent call last):
  File "/home/ion/artiq-dev/artiq/artiq/master/worker_impl.py", line 243, in main
    examine(ExamineDeviceMgr, ParentDatasetDB, obj["file"])
  File "/home/ion/artiq-dev/artiq/artiq/master/worker_impl.py", line 145, in examine
    exp_class((device_mgr, dataset_mgr, argument_mgr))
  File "/home/ion/artiq-dev/artiq/artiq/language/environment.py", line 207, in __init__
    self.build(*args, **kwargs)
  File "/home/ion/repo/tests/artiq/pyon_value.py", line 5, in build
    self.setattr_argument("test", PYONValue(default=[0,1,2,3]))
  File "/home/ion/artiq-dev/artiq/artiq/language/environment.py", line 30, in __init__
    raise NotImplementedError
NotImplementedError
```
This used to work - it looks like it was b3e55b7 added this new behaviour.

Is this an intentional side-effect? List defaults are rather useful for me.

**Comment by sbourdeauducq** [comment]
Not an intentional side effect. Feel free to propose a solution.
