### ISSUE TITLE
ImportError: cannot import name 'Keep' when installing artiq 2.2 from source

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#694]
I'm trying to install artiq 2.2 from source. Following the instructions, I run into this error message,

```
Using /home/rabi/anaconda3/envs/artiq-2017-03-28/lib/python3.5/site-packages
Finished processing dependencies for artiq==2.2+12.gbf86828
(artiq-2017-03-28)rabi@68810MAGTRAPVM:~/artiq-2.2/artiq$ cd ..
(artiq-2017-03-28)rabi@68810MAGTRAPVM:~/artiq-2.2$ python3.5 -m artiq.gateware.targets.kc705 -H nist_qc2
Traceback (most recent call last):
  File "/home/rabi/anaconda3/envs/artiq-2017-03-28/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rabi/anaconda3/envs/artiq-2017-03-28/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rabi/artiq-2.2/artiq/artiq/gateware/targets/kc705.py", line 11, in <module>
    from migen.fhdl.specials import Keep
ImportError: cannot import name 'Keep'
```

Seems like it installed this version of migen,

```
migen (/home/rabi/artiq-2.2/migen) 0.5.dev0                  <pip>
```

Any idea what I should do to resolve this?

**Comment by sbourdeauducq** [comment]
Install migen 0.4.
