### ISSUE TITLE
self.attr_argument("scan", Scannable(global_max=400, default=NoScan(325))) fails

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#83]
examples/master/repository/arguments_demo.py

```bash
Exception ignored in: rabi2@vboxartiq:~/artiq-dev/artiq/examples/master$ artiq_gui
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
Traceback (most recent call last):
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/gui/explorer.py", line 188, in update_argsetter
    self.argsetter = _ArgumentSetter(self.dialog_parent, arguments)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/gui/explorer.py", line 111, in __init__
    entry = _procty_to_entry[procdesc["ty"]](procdesc)
KeyError: 'Scannable'
Traceback (most recent call last):
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/gui/explorer.py", line 187, in update_argsetter
    self.argsetter.deleteLater()
RuntimeError: wrapped C/C++ object of type _ArgumentSetter has been deleted

**Comment by jboulder** [comment]
OK. This works with the latest version of ARTIQ on github. Will wait for new binstar build.
