### ISSUE TITLE
Compiler crash using unary operator

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#836]
Experiment:
```python
class UnaryCrash(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def run(self):
        x = ~1
```

Error:
```
Traceback (most recent call last):
  File "/home/artiq/artiq-dev/artiq/artiq/master/worker_impl.py", line 273, in main
    exp_inst.run()
  File "/home/artiq/artiq-dev/artiq/artiq/language/core.py", line 53, in run_on_core
    return getattr(self, arg).run(run_on_core, ((self,) + k_args), k_kwargs)
  File "/home/artiq/artiq-dev/artiq/artiq/coredevice/core.py", line 124, in run
    self.compile(function, args, kwargs, set_result)
  File "/home/artiq/artiq-dev/artiq/artiq/coredevice/core.py", line 104, in compile
    attribute_writeback=attribute_writeback)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/module.py", line 75, in __init__
    self.artiq_ir = artiq_ir_generator.visit(src.typedtree)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 176, in visit
    return self._visit_one(obj)
  File "/home/artiq/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 204, in visit_ModuleT
    self.generic_visit(node)
  File "/home/artiq/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 172, in visit
    self.visit(elt)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 176, in visit
    return self._visit_one(obj)
  File "/home/artiq/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 349, in visit_QuotedFunctionDefT
    self.visit_function(node, is_internal=True, is_quoted=True, flags=node.flags)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 311, in visit_function
    result = self.visit(node.body)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 172, in visit
    self.visit(elt)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 176, in visit
    return self._visit_one(obj)
  File "/home/artiq/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 378, in visit_Assign
    self.current_assign = self.visit(node.value)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 176, in visit
    return self._visit_one(obj)
  File "/home/artiq/anaconda3/envs/artiq-dev/lib/python3.5/site-packages/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/artiq/artiq-dev/artiq/artiq/compiler/transforms/artiq_ir_generator.py", line 1300, in visit_UnaryOpT
    assert False
AssertionError
```

**Comment by whitequark** [comment]
I forgot to implement it.
