### ISSUE TITLE
artiq_flash libusb_open() failed

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#928]
```
$ artiq_flash --target sayma --variant standalone --dir /home/britton/artiq-dev/artiq/artiq_sayma_with_drtio 
Design: top;COMPRESS=TRUE;UserID=0XFFFFFFFF;Version=2017.4.1
Part name: xcku040-ffva1156-1-c
Date: 2018/02/22
Time: 18:10:23
Bitstream payload length: 0xc46a7c
Open On-Chip Debugger 0.10.0-00013-gbb7beda (2018-02-13-15:56)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 5000 kHz
Error: libusb_open() failed with LIBUSB_ERROR_ACCESS
Error: no device found
Error: unable to open ftdi device with vid 0403, pid 6011, description 'Quad RS232-HS', serial '*' at bus location '*'

Traceback (most recent call last):
  File "/home/britton/anaconda3/envs/artiq-dev/bin/artiq_flash", line 11, in <module>
    load_entry_point('artiq', 'console_scripts', 'artiq_flash')()
  File "/home/britton/artiq-dev/artiq/artiq/frontend/artiq_flash.py", line 356, in main
    programmer.run()
  File "/home/britton/artiq-dev/artiq/artiq/frontend/artiq_flash.py", line 188, in run
    self._client.run_command(cmdline)
  File "/home/britton/artiq-dev/artiq/artiq/remoting.py", line 56, in run_command
    subprocess.check_call([arg.format(tmp=self._tmp, **kws) for arg in cmd])
  File "/home/britton/anaconda3/envs/artiq-dev/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['openocd', '-s', '/home/britton/anaconda3/envs/artiq-dev/share/openocd/scripts', '-c', 'source [find fpga/xilinx-xadc.cfg]; interface ftdi; ftdi_device_desc "Quad RS232-HS"; ftdi_vid_pid 0x0403 0x6011; ftdi_channel 0; ftdi_layout_init 0x0098 0x008b; reset_config none; adapter_khz 5000; transport select jtag; source [find cpld/xilinx-xc7.cfg]; set CHIP XCKU040; source [find cpld/xilinx-xcu.cfg]; target create xcu.spi0.proxy testee -chain-position xcu.tap; flash bank spi0 jtagspi 0 0 0 0 xcu.spi0.proxy 0x2; target create xcu.spi1.proxy testee -chain-position xcu.tap; flash bank spi1 jtagspi 0 0 0 0 xcu.spi1.proxy 0x3; gdb_port disabled; tcl_port disabled; telnet_port disabled; init; echo "RTM FPGA XADC:"; xadc_report xc7.tap; echo "AMC FPGA XADC:"; xadc_report xcu.tap; pld load 1 /home/britton/anaconda3/envs/artiq-dev/share/bscan-spi-bitstreams/bscan_spi_xcku040-sayma.bit; flash probe spi0; flash erase_sector spi0 0 196; flash write_bank spi0 /tmp/tmppl8nuw7u 0x0; flash verify_bank spi0 /tmp/tmppl8nuw7u 0x0; flash probe spi1; flash erase_sector spi1 0 1; flash write_bank spi1 /home/britton/artiq-dev/artiq/artiq_sayma_with_drtio/standalone/software/bootloader/bootloader.bin 0x0; flash verify_bank spi1 /home/britton/artiq-dev/artiq/artiq_sayma_with_drtio/standalone/software/bootloader/bootloader.bin 0x0; flash probe spi1; flash erase_sector spi1 5 13; flash write_bank spi1 /home/britton/artiq-dev/artiq/artiq_sayma_with_drtio/standalone/software/runtime/runtime.fbi 0x50000; flash verify_bank spi1 /home/britton/artiq-dev/artiq/artiq_sayma_with_drtio/standalone/software/runtime/runtime.fbi 0x50000; xcu_program xcu.tap; exit']' returned non-zero exit status 1
```

```
$dmesg
[21967.914720] usb 1-10: new high-speed USB device number 7 using xhci_hcd
[21968.055321] usb 1-10: New USB device found, idVendor=0403, idProduct=6011
[21968.055327] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[21968.055330] usb 1-10: Product: Quad RS232-HS
[21968.055334] usb 1-10: Manufacturer: FTDI
[21968.056081] ftdi_sio 1-10:1.0: FTDI USB Serial Device converter detected
[21968.056135] usb 1-10: Detected FT4232H
[21968.056322] usb 1-10: FTDI USB Serial Device converter now attached to ttyUSB0
[21968.056482] ftdi_sio 1-10:1.1: FTDI USB Serial Device converter detected
[21968.056528] usb 1-10: Detected FT4232H
[21968.056698] usb 1-10: FTDI USB Serial Device converter now attached to ttyUSB1
[21968.056856] ftdi_sio 1-10:1.2: FTDI USB Serial Device converter detected
[21968.056908] usb 1-10: Detected FT4232H
[21968.057056] usb 1-10: FTDI USB Serial Device converter now attached to ttyUSB2
[21968.057200] ftdi_sio 1-10:1.3: FTDI USB Serial Device converter detected
[21968.057244] usb 1-10: Detected FT4232H
[21968.057415] usb 1-10: FTDI USB Serial Device converter now attached to ttyUSB3
```

**Comment by sbourdeauducq** [comment]
> Error: libusb_open() failed with LIBUSB_ERROR_ACCESS

Permissions problem. You need to fix your groups and/or udev rules. http://m-labs.hk/artiq/manual-master/installing.html#configuring-openocd
