### ISSUE TITLE
compiler crash when function type annotation is present

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#987]
Not a critical problem, but the error message should be better.

```
from artiq.experiment import *

class Test(EnvExperiment):
    def build(self):
        self.setattr_device("core")

    @kernel
    def hello(self, x: None):
        pass

    @kernel
    def run(self):
        self.hello(2)
```

```
$ artiq_compile.py test.py                    
Traceback (most recent call last):
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 600, in _unify_attribute
    attributes, attr_value_type = self.attr_type_cache[attr_type_key]
KeyError: (140686594769472, 'hello')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sb/artiq/artiq/frontend/artiq_compile.py", line 76, in <module>
    main()
  File "/home/sb/artiq/artiq/frontend/artiq_compile.py", line 58, in main
    attribute_writeback=False, print_as_rpc=False)
  File "/home/sb/artiq/artiq/coredevice/core.py", line 104, in compile
    stitcher.finalize()
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 698, in finalize
    inferencer.visit(self.typedtree)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 39, in visit
    return [self.visit(elt) for elt in obj]
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 39, in <listcomp>
    return [self.visit(elt) for elt in obj]
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/sb/artiq/artiq/compiler/transforms/inferencer.py", line 1309, in visit_FunctionDefT
    self.generic_visit(node)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 39, in visit
    return [self.visit(elt) for elt in obj]
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 39, in <listcomp>
    return [self.visit(elt) for elt in obj]
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 34, in _visit_one
    return self.generic_visit(node)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/sb/artiq/artiq/compiler/transforms/inferencer.py", line 923, in visit_CallT
    self.generic_visit(node)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 27, in generic_visit
    self.visit(getattr(node, field_name))
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 41, in visit
    return self._visit_one(obj)
  File "/home/sb/pythonparser/pythonparser/algorithm.py", line 32, in _visit_one
    return getattr(self, visit_attr)(node)
  File "/home/sb/artiq/artiq/compiler/transforms/inferencer.py", line 94, in visit_AttributeT
    loc=node.loc)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 603, in _unify_attribute
    self._compute_attr_type(object_value, object_type, object_loc, attr_name, loc)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 581, in _compute_attr_type
    ast = self.quote(attr_value, object_loc.expanded_from)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 1077, in _quote
    node = synthesizer.quote(value)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 250, in quote
    function_type = self.quote_function(value, self.expanded_from)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 1059, in _quote_function
    flags=host_function.artiq_embedded.flags)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 856, in _quote_embedded_function
    arg_type = self._type_of_param(function, loc, param, fn_kind='kernel')
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 792, in _type_of_param
    fn_kind)
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 928, in _extract_annot
    self._function_loc(function),
  File "/home/sb/artiq/artiq/compiler/embedding.py", line 752, in _function_loc
    filename = function.__code__.co_filename
AttributeError: 'SpecializedFunction' object has no attribute '__code__'
```

**Comment by whitequark** [comment]
Well, the actual problem here is that your type annotation is nonsensical. ARTIQ Python only accepts type annotations from `artiq.compiler.types`.

**Comment by sbourdeauducq** [comment]
That should be documented; at the minimum the error message should point that out.

**Comment by whitequark** [comment]
> at the minimum the error message should point that out

Of course. I'm just explaining.

**Comment by whitequark** [comment]
And there was a proper error message, it was just failing on this function for an unrelated reason.
